### ISSUE TITLE
Session inheritance - filed in debian bts

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#110]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895318
Imho recent files are enough for a lightweight editor - maybe you see this different :)

**Comment by tsujan** [comment]
That seems like a valid feature request. Why reporting there and not here?!

> Imho recent files are enough for a lightweight editor

I prefer and use recently closed files but I don't open recent files with the new session -- that was a feature requested a long time ago. BTW, FeatherPad is as lightweight with both as with one of them.

Anyhow, thanks for putting the report in the right place! I'll look into it.

**Comment by agaida** [comment]
It might be useful - i never used such features in the past very often, but as i wrote in the debian bug, there is nothing what i want to do downstream. :)

**Comment by aramazano** [comment]
Apologies for filing it with Debian. I have explained the reason at
https://github.com/lxqt/pcmanfm-qt/issues/636#issuecomment-379932867

My reason for the feature request was that, I have never needed "start with recent files" (why would I want to re-open on startup some file that I had already closed?) but I have always needed to restart with the "last active session". That is because I usually work with numerous files and I keep them open all the time (even if I use some of them once in a week). These set of files are analogous to open notebooks on my working desk space. So, I need them be carried over from one sitting to the next.

As far as I am concerned, the preference "Start with recent files: [NN files]" can even be replaced by (instead of existing besides) a "start with last active session" checkbox " - in case there is no one actually wanting "start with recent files" feature.

Thank you and regards.

**Comment by tsujan** [comment]
An example. This is how I develop Kvantum with FeatherPad (+ Qterminal):

![kvantum](https://user-images.githubusercontent.com/981076/38532110-7c14073c-3c88-11e8-9269-962fa8eb0786.png)

The work will be resumed the next time in the sense that cursor positions are remembered for all session files.

Now, I think it might just be better to check "Save only from this window" by default.

**Comment by aramazano** [comment]
To be honest, I have read about and tried out the session save/restore feature, but not much used it. The reason that I prefer restoring the last active session to saving/restoring a named session is that I find the former more convenient.

My list of open files evolve by time. Some of them I add/remove from the list randomly, some of them in bulk (when I focus on a project). They are all mixed up, so I can't maintain a predefined list. With session save/restore feature, each time I add or remove a file to/from the list, I need to save the session before quitting featherpad for later restoral. With "restore last active session" feature I can just quit featherpad as-is, and when I relaunch featherpad I can continue from where I have left.

Session save/restore has an added benefit of keeping cursor positions, which "open recent files" lacks. So I surmise that handling the active session as a special kind of "saved session" would also take care of cursor positions.

BTW I always work with only one window, so maybe "start with last active session" could possibly introduce complexities in a multi-window environment - I 

As I have little hands-on experience with session save/restore feature, I can mostly theoretically evaluate it as of now. I will regularly use it for some time and see how I go about it.

**Comment by tsujan** [comment]
> I find the former more convenient.

It may be so *only with your very special use case* -- and even so, not much. Other than that, it would be an obvious hassle if the last closed files were supposed to be opened next time, regardless of what they really are (as I said, I might remove that setting). IMO, a session makes sense only with files that are somehow important to the user. For random files, we have the recently opened/modified menu. And there's no way to distinguish "random" from "important" other than saving a session consisting of the latter.

The session manager may need 2 more features: (1) The above-mentioned checkbox should be checked by default; and (2) it *may* be better to remember that last active item/tab too; I should think about that.

**Comment by aramazano** [comment]
I was a bit too terse with the term "random files". What I meant was, for instance, I have some weekly and monthly log files, create a new file each week and I keep last 3 or 4 of them open together for quick back-referral. Also have some files that are open throughout the year. Some files when I am into something. Some project, some recipe, some music... they can bring several files to the list for a couple of hours to months. There are consistently open files, as well as there are spurious ones. It is somewhat difficult to explain all my file use cases because there are many of them, but when I sum them all up, that produces a regularly evolving/changing list, eventually making "restore last session" very handy for me.

BTW I have tried to simulate "restore last session" with "session save/restore" feature. My initial experience is as follows:

I saved the current session as "aktif" and disabled "open recent files".

-------

With session save/restore feature:

Initial launch -> Empty list.

*Restore session*
Press: Ctrl-M
Doubleclick: "aktif" -> Session restored

Change files list by closing some files, opening other files.

*Save session*
Press: Ctrl-M
Type: "aktif"
Press: [Save] --> Overwrite warning message appears
Press: [Yes]

Quit and relaunch featherpad Empty list.

*Restore session*
Press: Ctrl-M
Doubleclick "aktif" -> Session restored

-------

The same workflow with "restore last session" would have been:

Initial launch -> Session restored.

Change files list by closing some files, opening other files.

Quit and relaunch featherpad -> Last session restored.

**Comment by tsujan** [comment]
No, sessions aren't for that; their purpose is totally different.

I'll think about it. If it can replace "Start with recent files" in a clean way, why not? After all, that setting isn't good in its current form, as you truly mentioned.

**Comment by agaida** [comment]
only two thoughts- "default" session and a session autosave feature - done :D

**Comment by tsujan** [comment]
@agaida Like `pcmanfm-qt` in the daemon/desktop mode, there's nothing but the current session. If you open several FeatherPad windows, you'll see only one `featherpad` process; all windows are treated on an equal level but only one window can be *the last window*.

Anyhow, I implemented it 10 hours ago :) just needed some rest after that. Will polish and push it later.

**Comment by tsujan** [comment]
Implemented in https://github.com/tsujan/FeatherPad/commit/39904eb8ad1749c8e32a3ff89a17e6ae207ddf2b as "Start with files of last window", under `Preferences → Files`. The term "session" is skipped intentionally.

As is mentioned in its tooltip/"WhatsThis", the file list will be restored only if it contains ≤ 20 files. Restoring a window with more than 20 files not only could be CPU-intensive but doesn't make much sense either, unless it's handled by the session manager directly.

All in all, this is much better than the previous option. Thanks for the detailed description of this use case!

**Comment by aramazano** [comment]
@tsujan Yay! Thank you very much! I will try it out as soon as it appears in Debian Unstable.

> unless it's handled by the session manager directly.

Does it have implications on retaining previous cursor positions?

**Comment by tsujan** [comment]
@aramazano

Now, cursor positions are restored with last window files too.

BTW, you don't need to update your translation fork. Just tell me whenever your translation is complete.

**Comment by aramazano** [comment]
> the file list will be restored only if it contains ≤ 20 files. 

Hmm I have just stumnled upon something: When my last session contains > 20 files, then *nothing* is restored at the next run - simply starts up with an empty session. Any workaround possible for this? E.g. launching with the "newest" 20 files or something like that?

**Comment by aramazano** [comment]
I don't know how it is done for saved sessions (which have no limits) but even if it is more CPU intensive than restoring a saved session, the user can be told "you asked for it, you got it" :)

He can be allowed to pay the price for what he wants of the system, that is, number of files limit can be waived - like in saved sessions.

**Comment by aramazano** [comment]
Or, alternatively, the last active session can be handled just like a special (default) kind of a saved session. In that case, whatever property a saved session has, last active session has.

**Comment by tsujan** [comment]
> Or, alternatively, the last active session can be..

The last session is the empty one.

I agree that there's a problem here: the user closes a window with 21 files and the next time no file is opened. The best solution that comes to my mind is forgetting the files after the 20th one when closing the window. Since tabs are closed from the end to the start, that means first files will be forgotten.

**Comment by tsujan** [comment]
With the above solution, I'll make it 50 files - but not more.

**Comment by tsujan** [comment]
Done it https://github.com/tsujan/FeatherPad/commit/0ac326158c71cbda107364cbcf597e67d973fda5

Which means, at most 50 files will be remembered an if they are more that 50, 50 of them (the last ones) will remain n the list.

**Comment by agaida** [comment]
maybe a hint about the limit is useful

**Comment by tsujan** [comment]
> maybe a hint about the limit is useful

There is one, as a tooltip.
