### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by aramazano** [tsujan/FeatherPad#111]
Hello,

I would like to volunteer for Turkish translation of featherpad. I have no previous translation experience but I think it wouldn't be an issue for me. I will just take cues from other (already translated) packages for the general jargon and improvize on them. I don't know which tools to use (if any), though.

How should I go about this? Pointers and directions are appreciated.

Thanks and regards.

**Comment by tsujan** [comment]
That's good news. FeatherPad needs a Turkish translation.

It isn't hard -- except for the translation part ;) Please read the last section of the file `INSTALL`. All the needed info is there. You should install Qt Linguist and use it for translation.

**Comment by aramazano** [comment]
@tsujan Thank you! I will try it. :)

**Comment by tsujan** [comment]
You're welcome.

BTW,

(1) FeatherPad is a single-instance multi-window app. So, like @palinek said about pcmanfm-qt at https://github.com/lxqt/lxqt/issues/1475#issuecomment-380649029 , you couldn't see 2 translations at the same time.

(2) Qt Linguist will make translation much easier for you. *Always use Qt Linguist for translating any Qt app.*

(3) Please use the latest git source of FeatherPad for translation, as far as possible.

(4) After I merge your future PR (pull request), please take a look at the latest git source of FeatherPad once in a while -- once a month at most -- to see if more translation is needed because new texts might be added to the GUI. It'll be enough to open your merged translation file with Qt Linguist because the new (English) texts will be added to it if needed.

Thanks in advance!

**Comment by aramazano** [comment]
@tsujan

Referring to the arrow keys (e.g. Ctrl+Right) what would you think about using,

[←] [↑] [→] [↓] or [⇦] [⇧] [⇨] [⇩] ?

E.g. Ctrl+[↑] or [Ctrl]+[⇧] or [Ctrl][⇧] etc.

These are Unicode 1.1 additions so I assume they ought to work virtually on every platform. They use universal iconic language, copycat the keyboard symbols, don't need translation (can be hard coded).

⇧ or ⇩ ? :)

Another thing is, I'm contemplating about translating data/help text too (possibly as help_tr). What would you think about it?

**Comment by tsujan** [comment]
I know about those characters but writing them as Ctrl+Right, Ctrl+Left... is standard.

As for Help, I don't intend to make it translatable because it's too long and isn't essential for using FeatherPad.

**Comment by tsujan** [comment]
@aramazano Thanks a lot for the hard work! I'll check the PR tomorrow.

As for the details, I completely understand that translating can never be done word by word. It'll be enough and OK if the meanings are clear to Turkish native speakers, which I'm sure will be the case with your translation.

> There are some missing translations such as:...

Qt is responsible for them, not FeatherPad. They are standard objects added by Qt and, I think, if all Qt translation files (`qt5-translations` in Arch-based systems) are installed, they will be translated automatically.

**Comment by tsujan** [comment]
BTW,

> "Clear the list of recently modified files" seems to be used for both recently opened and modified files.

You're right but that tooltip isn't shown. I'll remove it sooner or later.

You could edit your translation in whatever way you see fit and make PRs. If you do so, please fork/branch the latest FeatherPad source. Thanks again!
