### ISSUE TITLE
copy/paste line end

### ISSUE THREAD

**Issue by p8q** [tsujan/FeatherPad#115]
Is it possible not to copy line ends in FeatherPad?

For instance pasting several lines in a new file on github.com makes every second line empty.

**Comment by tsujan** [comment]
> For instance pasting several lines in a new file on github.com makes every second line empty.

That may be because github uses markdown.

The line-ends are parts of the text and it would be wrong (or rather a bug) if they were removed while copying. For example, what if I want to copy a text from one file to another? That's a usual use case.

It's easy to remove line-ends from a (part of a) text: (1) copy and paste the line-end in to the first line-edit of the Replace dock, (2) put a space or some other characters into the second line-edit, and (2) and do replacing. Usually I do the inverse, though ;)

BTW, thanks a lot for the German translation! I'll merge it tomorrow.

**Comment by tsujan** [comment]
Oh, as for pasting from github, I saw it. Again the solution was easy: I replaced 2 line-ends with one at once (with `F9`).

**Comment by p8q** [comment]
I completely agree, line ends are parts of the text, and need to be copied.
I only remember Leafpad managed it somehow different, never mind.

As for translation. You're welcome! It's a first draft with a lot of bugs for sure.
Hopefully it will still be useful.
