### ISSUE TITLE
Somewhat wrecks -w after the last commits

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#131]
http://i.imgur.com/Kp3ErHu.png

**Comment by tsujan** [comment]
My bad! I forgot to test the simplest things after that change! Apparently, I won't read PCMan's commit today.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/8c37cad5b1c33c88edc839bc2705ffcd77e83e4a

Illogical cases like `fpad +3,8` (without file) are also covered and a message is shown in the terminal of the main process. I didn't trust Qt's commandline parser for that.

Silly mistakes aren't impossible ;)


BTW, I've found a strange thing in Qt or Linux kernel, which is a real mystery to me (hence the long delay -- was busy with it). If you have any idea about it, please tell me!

Sometimes, I drop 240 items in `/usr/share/applications` into FP to test it. On my laptop, it usually takes ~20 sec for them to be completely shown (faster than Kate). However, sometimes, it takes only 5 sec, although I haven't done it since boot!

The mystery is, if Qt or kernal can do it sometimes, why not always? And what if it can be enforced?

**Comment by tsujan** [comment]
Also, dealt with relative paths from terminal when FP is already running (they weren't seen correctly before).

**Comment by agaida** [comment]
cool, thanks - save me from writing a bug about, has noticed it but not analyzed yet :)

**Comment by agaida** [comment]
tested a bit now - for me it is fine

**Comment by agaida** [comment]
> The mystery is, if Qt or kernal can do it sometimes, why not always? And what if it can be enforced?
not really a clue - maybe some kind of caching mechanism that we don't know?

**Comment by tsujan** [comment]
>  maybe some kind of caching mechanism that we don't know?

That came to my mind too. When all tabs, search-bars, text-edits are like each other, why creating them from scratch? But that's just a sci-fi thought.

**Comment by tsujan** [comment]
"Super fast loading" happened again! Damn! It's possible but hidden.

**Comment by tsujan** [comment]
FYI:

Found the cause for "Super fast loading":

With `mq-deadline` I/O scheduler, it's sometimes fast, sometimes not. I changed the scheduler on my spinning drive (my SSD has no schedule and only contains root) to `bfq` and now, it's always super fast :)
