### ISSUE TITLE
Change syntax highlighting colors?

### ISSUE THREAD

**Issue by paul1149** [tsujan/FeatherPad#145]
Really enjoying FeatherPad, on MX Linux. Light, but with very good feature set!

Is it possible to change the syntax highlighting colors? My main problem is the orange comments. I don't think comments should stand out more than basic text. I would go with more of a gray.

Also, although this is probably outside the province of any one app, is there an instruction on how to find and apply a QT theme? I like the Kvantum theme shown in the screenshots.

Thanks much.

**Comment by tsujan** [comment]
Glad to know that FeatherPad is useful to you.

> Is it possible to change the syntax highlighting colors?

Unlike other text editors, FeatherPad does syntax highlighting in its own code, without being dependent of any outside library for it. There are so many colors in the code and they're carefully chosen so that they're both clearly visible and different from each other. The syntax parts they cover are *too many* for them to be customizable. So, I have no plan for syntax color customization yet. However, I should think about a plan at some point.

> Also, although this is probably outside the province of any one app, is there an instruction on how to find and apply a QT theme?

I recommend [Kvantum](https://github.com/tsujan/Kvantum), of course. It comes with many themes.

**Comment by paul1149** [comment]
Ok, thanks much. I can't figure how to use Kvantum on xfce, so I'll leave things the way they are.

BW.

**Comment by tsujan** [comment]
> I can't figure how to use Kvantum on xfce

xfce is a GTK-based DE. So, you need to install a Qt5 config tool like `qt5ct` and choose Kvantum from it. Then, the Kvantum default theme will be used with Qt apps. To change the Kvantum theme, use Kvantum Manager.

**Comment by dwrl** [comment]
Hello,
sorry to chip in this late, but I just looked how to change syntax colors and arrived here.
Let me say first say I'm not really into c++, more of a python guy, but I had a quick look at highlighter.cpp, and as far as I can see, the colors are defined in lines 218 to 254. It might be enough for most people to outsource the color definitions into a text file, i.e.:


_~./.config//termite/syntax-colors.rc:_

`[colorScheme]
mainFormat = (1,1,1)
neutralFormat = (1,1,1)
Blue = (0,0,255)
DarkBlue = (0,0,128)
Red = (255,0,0)
DarkRed = (150,0,0)
Verda = (0,110,110)
DarkGreen = (0,128,0)
DarkMagenta = (128,0,128)
Violet = (126,0,230)
Brown = (160,165,165)
DarkYellow = (128,128,0)
Faded = (165,165,165)
translucent = (0,0,0,190)

[darkColorScheme]
mainFormat = (255,255,255)
neutralFormat = (254, 254, 254)
Blue = (85, 227, 255)
DarkBlue = (65, 154, 255)
Red = (255, 120, 120)
DarkRed = (255, 160, 0)
Verda = (150, 255, 0)
DarkGreen = (0,255,0)
DarkMagenta = (255, 153, 255)
Violet = (255, 255, 0)
Brown = (255, 200, 0)
DarkYellow = (255,255,0)
Faded = (105, 105, 105)
translucent = (255, 255, 255, 190)`

and just get the values from there, like it is done on the terminals _(if you look f.e. [here](https://github.com/khamer/base16-termite/tree/master/themes), people do just redefine 'green' to be whatever they like and be done with it, while the terminal of course couldn't care less)_.
Anything else isn't changed at all, you put a disclaimer at the top of the file, and if the user ends up with an unreadable mess in his featherpad, well, his responsibility/fault ;)

Seems like this way the effort would be as small as possible, with the greatest effect.
Then again, I don't really speak C, so I might be completely off in regards to the amount of work this would need.

**Comment by tsujan** [comment]
@dwrl 

At some point, I'll make the colors customizable but not soon.

As you correctly mentioned, some colors are defined in `highlighter.cpp` but the definitions aren't complete. Moreover, the color that's used for quotes, for example, may have been used for other purposes in languages without quote highlighting (there are some).

But *most importantly*, I should add some codes to prevent identical custom colors -- and this part will be very boring ;) The reason is that FeatherPad's compact syntax highlighting relies on differences between some colors -- otherwise, it couldn't be compact.

That can be done in 2 ways: not applying custom colors with identical colors among them, or changing one or more identical colors slightly (by changing R, G or B only by one unit).

All this will take time. For now, I prefer to focus on implementing/testing more important/practical features -- like regex search, which I added recently.

Thanks for your suggestions!

> Then again, I don't really speak C, so I might be completely off in regards to the amount of work this would need (or have completely misunderstood the code, it happens xD).

On the contrary, you told about something I'd thought about, which means you saw through that complex code easily.

However, lots of boring work should be done; their logic will be straightforward but they should be done with the utmost care.

I might reopen this report whenever I start to work on it.
