### ISSUE TITLE
Filename in window title

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#157]
Please test:  set a hook in Preferences > Window > Do not show a single tab 

open exactly one file, go away for an hour.

Which file you are editing? :sunglasses:

**Comment by tsujan** [comment]
I know and never use it but what do you propose? Setting the file name on the titlebar wouldn't be a solution because the path may be long and the name may be inside "...". I added that option because some users wanted it.

**Comment by tsujan** [comment]
OK, I'll add the file name to the window title in this special case. Apparently, there's no other way.

That being said, I don't think this is an important issue. If the user forgets what he's editing, he could open an empty tab or switch to the side-pane mode temporarily.

**Comment by p8q** [comment]
The filename in window title is mandatory,
specially if you don't use tabs and always open in separate windows,
because it is also the label for lxqt-panel taskbar tasks.

But even if you use the default configuration, please test:
open a file and minimize it,
then open another file with pcmanfm-qt in the same directory.
You will get two windows and two lxqt-panel taskbar tasks labeld with the same path.

To display the path is handy in some use cases, but is the window title the right place for it?

**Comment by tsujan** [comment]
@p8q, very good point! Half an hour ago, I started the hard task of adding the file name when needed and removing it when not needed -- pretty complex. So, instead, I'll add it for all cases :)

**Comment by tsujan** [comment]
> To display the path is handy in some use cases, but is the window title the right place for it?

@agaida and I agreed that it's always needed.

**Comment by agaida** [comment]
nice :)

**Comment by agaida** [comment]
Will file another nice bug today - hopefully not to complicated - but a bit annyoing. Beside that featherpad works great. Replaced nano and vi for debian changelogs and commit messages completely :)

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/f425f4d6233caf550aa5d6e28018ec5d27b5fdc0
