### ISSUE TITLE
Enhancement request - Run script funtionality

### ISSUE THREAD

**Issue by xircon** [tsujan/FeatherPad#17]
As title - the ability to run a script (in my case Python) directly from the editor.  Is this possible?

Stumbled across Featherpad in the Manjaro forum - very impressed.  Been using Atom but it is so slow to load, it is pointless as a general purpose editor.

**Comment by tsujan** [comment]
First, thanks for the suggestion!

FeatherPad wasn't intended to be an IDE but a light text editor with good syntax highlighting, search/replace, line numbering, etc. I always use it when coding (because it's more comfortable than IDE's to me) but I use a terminal for compilation and running. I don't think adding an option to open a terminal and run a script would be really useful.

**Comment by xircon** [comment]
OK, understand.  Probably me being lazy :)

**Comment by tsujan** [comment]
It's OK. I made FeatherPad because of my "laziness" -- working with Kate made me nervous ;)

With the next commit, I'll add a lot of built-in Python functions and keywords to syntax highlighting after some tests.
