### ISSUE TITLE
Syntax highlighting - does not show on newly saved files

### ISSUE THREAD

**Issue by xircon** [tsujan/FeatherPad#20]
What I did:

* Opened a new file - ctrl+n
* Type some python code
* Save as something.py

The code remains unhighlighted.

Save/Close/re-open code becomes highlighted.

**Comment by tsujan** [comment]
In such cases you could just use the Reload button (or Ctrl+Shift+R).

FeatherPad doesn't know in what language a newly created text is written until it's reloaded after being saved. Saving alone doesn't mean reloading. If you create an empty Python file, open it and write the code, it'll be highlighted instantly.

However, please don't close this issue because, although I never saw this as a problem, I changed my mind after your report. I'll try to add lines of code to detect the language and highlight text after saving a newly created doc.

**Comment by tsujan** [comment]
Done!
It was a little tricky and I was very drowsy ;) So, although I tested it several times, your test is really needed. Please also see if the syntax part of the statusbar text (Ctrl+Shift+D) is correct after saving!

**Comment by xircon** [comment]
Again, thanks! Works perfectly:
![image](https://cloud.githubusercontent.com/assets/1316691/23607339/78b5e84c-025c-11e7-8192-043068948b1b.png)

**Comment by tsujan** [comment]
It works but, since this change was really tricky, there are still small problems that you may not encounter easily. I'll try to fix all of them today. Please update your FeatherPad installation tomorrow!

**Comment by xircon** [comment]
Do you ever sleep?

**Comment by tsujan** [comment]
> Do you ever sleep?

LOL! I wanted to but didn't have time 😂
