### ISSUE TITLE
Featherpad forgets layout each time

### ISSUE THREAD

**Issue by lucasart** [tsujan/FeatherPad#204]
Each time I start, I need to redo the following actions:
* Options -> Line Numbers
* File -> Side-Pane
* Options -> Preferences -> Window -> Show cursor position on status bar

Shouldn't Featherpad remember that automatically ?

**Comment by JohnD-** [comment]
Using Featherpad in Lubuntu 18.10 over here and also having same preference saving problems.
In my case it was while attempting to get the dark Color Scheme. Reopening application resulted in the default bright background.
Just wanted to verify that its happening to more than just one user :)

**Comment by tsujan** [comment]
> remember previous settings automatically.

Never! Side-pane can be used temporarily; it shouldn't persist just because the user starts to use it.

> an do so silently

IMO, a good app does nothing silently -- not under Linux, at least.

> This would also reduce signigicantly the number of options

That isn't my goal. It's the goal of Gnome developers: they love removing options and have the illusion that they know what's best for their users.

> ie. make featherpad more like a simple notepad to use

FeatherPad isn't a simple text editor. It wasn't suppose to be a simple notepad.

> Using Featherpad in Lubuntu 18.10

Lubuntu is known for changing sources (irresponsibly). So, Lubuntu bugs should be reported to Lubuntu maintainers.

**Comment by tsujan** [comment]
And don't mistake "plain-text editor" with "simple text editor" (plain-text vs. rich-text).
