### ISSUE TITLE
Enhancement - Session Management/Recent Files

### ISSUE THREAD

**Issue by xircon** [tsujan/FeatherPad#22]
Featherpad launches with a blank session, would it be possible to have a recent files section in the file menu, or to have it launch with the last session open?

**Comment by tsujan** [comment]
You're bombarding FeatherPad with good suggestions! I don't know why they didn't occur to *me*.

OK, I'll think about it -- the next release should be delayed again ;)

**Comment by tsujan** [comment]
Done, in a way.

Once the new option is enabled, FeatherPad will save the path of *the last modified file in a session* and will open it on an empty startup in the next session if the file still exists and is readable. Removed/invalid paths will be forgotten.

Here, "session" means a set of FeatherPad windows. The session ends when all windows are closed. An "empty startup" means opening the first FeatherPad window without giving it any file.

If this isn't what you meant, please elaborate!

**Comment by xircon** [comment]
Sort of what I mean.  If for example, I am editing a system file (or several sometimes) I need to reboot to make the changes, I would like the file(s) to be there.  Medit does this.  I run KDE mainly, but still use Medit because of this feature.

Here is a screenshot of Medit immediately after launch:
![image](https://cloud.githubusercontent.com/assets/1316691/23657359/94fcc1cc-0335-11e7-9cba-67f549f85d94.png)
As you can see it has the files I was last working on.

As for recent files this is what I mean (just an example):
![image](https://cloud.githubusercontent.com/assets/1316691/23657282/35ab21a0-0335-11e7-8380-d2173b45c4de.png)

Am on my way out, will report back later am just updating featherpad from AUR.

**Comment by tsujan** [comment]
After my last comment, I started to work on this (which seems similar to what you described):

(1) The new option (Start with the last modified file) will remain intact;
(2) A menu-item with the title "Open Recent Modified" will be added to the File menu. It'll contain the most 10 recent *saved* files.

The difference from the above screenshot is that unsaved files won't be included. My reason is that this is a text *editor* and if a file isn't saved, there's no reason to include it.

Is that acceptable to you?

**Comment by xircon** [comment]
Absolutely - the only thing I would like (if possible) is files not file, but if recent menu contains last 10 saved files that will work as well.  Talk later, must get going.

**Comment by tsujan** [comment]
Done in the best way :)

(1) There's always a "Recently Modified" menu under the File menu. It can have ten entries at most but that could be set as an option later (although I think 10 is enough);

(2) At most 10 recently modified files can be opened simultaneously with an empty startup. The option has a spinbox, with 0 (default) for not opening any file at startup.

A screenshot:

![rmm](https://cloud.githubusercontent.com/assets/981076/23686494/259df294-03bf-11e7-8e78-7f856676a6eb.png)


Please test whenever you have time!

**Comment by pmattern** [comment]
The new feature "Recently Modified" is working as expected here. Yet I for one would find it better if this topic didn't rely on files being modified but simply on being opened, in other words if it was turned into a topic "Recently Opened".

Btw. I'd love to see some feature like this in FeatherNotes as well.

Implementing session management by saving numbers of documents to be reopened seems a bit odd to me as I do not think this reflects a too common use case.
IMO the more common thing to do is either start with an empty window or restore exactly the same set of documents which was opened when FeatherPad was quit the last time before, so roughly the behaviour of Firefox setting "Show my windows and tabs from last time".
It would even be better when several sessions like this could be saved by arbitrary names and then restored by a command line switch, so roughly the behaviour of [g]vim command `mksession:` and CLI switch `-S`. Don't know whether this could be implemented in FeatherPad with reasonable effort, though.

**Comment by tsujan** [comment]
@pmattern 
Thanks for testing!

IMO, with a text editor -- in contrast to a web browser or PDF viewer -- modification is more important than opening. Any file manager could be used to find and open documents; with a text editor, it's more important to know which files are recently edited. Hence "Recently Modified" instead of "recently Opened".

As for saving sessions, I though about it. The main question is the meaning of a "session". FeatherPad is a single-instance app; all of its open windows are parts a the same process. Now, a session could mean all open windows with all their tabs, or all tabs in a single window where a session is saved. I think the latter is more practical. What do you think? And since a saved session would include all tabs of a window -- modified or not -- it would complement the "Recently Modified" menu.

Anyway, in the last two days, I was busy with an extensive (offline) change to FeatherPad. Technical matters aside, it's about 2 things:

(1) The remainder of the old C structure of the code is removed;
(2) The search undo/redo history is preserved and tabs are made completely independent with regard to searching.

Lack of (2) had made me angry several times ;) I though it should be there before the next release. Since the change is big, I'm rereading and testing it before making a commit.

**Comment by pmattern** [comment]
Considering opening vs. modification of files may be a matter of taste to some degree, yet I still disagree.
Frequently I for one open files just to look something up or copy (from those files, not into them). Obviously these files aren't modified at such occasions, yet it would be convenient to have them at hand in a menu topic like we're discussing here.
Also, both kwrite and medit are considering the opening of files only in their corresponding topic of menu "File", not any modification.

As for defining "session" I think the only reasonable way is the instance as a whole, that is all windows and all tabs therein.
This is how e. g. medit is defining its "sessions" as well.

> Anyway, in the last two days, I was busy [...]

This is pretty much polish stuff. No hurry, no pressure, no nothing.

**Comment by tsujan** [comment]
> Considering opening vs. modification of files may be a matter of taste to some degree,

I agree. For example, I work with C++/C files and want to find quickly those I've modified. That functionality would be lost with "Recently Opened". On the other hand, if session can be saved, opened files will be included too. So, everything will be covered by these 2 features.

> This is how e. g. medit is defining its "sessions" as well.

As far as I remember, medit had just a single window. A single FeatherPad process can have multiple windows, each of which with multiple tabs (the session will be closed only if all windows are closed). If I add a "Save file list" and a "Open file list" to the File menu, the user could save the list of opened files in each window separately and under different names. Different lists could be opened in the same window or (by tab drag-and-drop or desktop switching) in different ones.

**Comment by pmattern** [comment]
> As far as I remember, medit had just a single window.

No. medit allows for several windows per instance and even comes with a topic "New Window" in its menu "File" which opens an empty document in a new window. Term "session" corresponds with all those windows and their tabs.

> On the other hand, if session can be saved, opened files will be included too. So, everything will be covered by these 2 features.

I don't think so. Re-opening files which had been open short ago can be useful independently of the session management.

Maybe an item "Recently Opened" as it can be seen in all kinds of other applications and current item "Recently Modified", which doesn't exist like this in any other application I'm aware of, could be implemented in parallel?
This would be some combination which doesn't exist so far which doesn't necessarily mean it doesn't make sense.

That aside, I've nothing new to add. I still think term "session" should correspond with the totality of all windows and tabs therein and cannot see any benefit of some list of files which should be opened in a particular window.

**Comment by tsujan** [comment]
@pmattern 

I made the big changes I'd mentioned above. They're mostly hidden to the user -- except for independent search arrangement and history per tab and also some fixes.

> Maybe an item "Recently Opened" ... and current item "Recently Modified" ... could be implemented in parallel?

Yes they could. My concern is about RAM and CPU usage at startup. I really like FeatherPad to remain light. Reading two lists, each with a maximum of 20 entries, at startup may not be a good idea. I know that "Recently Modified" is something new but since I added it, I've found it useful.

Maybe the best compromise is making them mutually exclusive in Preferences, with "Recently Modified" as the default.

>  I still think term "session" should correspond with the totality of all windows and tabs therein and cannot see any benefit of some list of files which should be opened in a particular window.

OK. The only thing than remains is how to add it to the current GUI. I have to think about it before starting to work on it.

**Comment by pmattern** [comment]
If providing two lists "Recently {Modified,Opened}" in parallel may cause a performance penalty, which I wouldn't have expected, then making them mutually exclusive including a preferences option as depicted above may indeed be the best solution.
A list like "Recently Modified" can certainly make sense even it hasn't been implemented in other text editors so far.

**Comment by tsujan** [comment]
> .... making them mutually exclusive including a preferences option as depicted above may indeed be the best solution.

Good! It's a way of adding more options to an app without making it heavier. I'll implement it soon.

**Comment by tsujan** [comment]
Done! Now there are recently opened files. The default is my favorite, namely "Recently Modified" ;) Switching between them clears the list and starts anew but doesn't need an app restart.

Should add a message dialog for those settings that need app restart to take effect; tooltips aren't enough.

**Comment by pmattern** [comment]
All working as described in your previous comment here.

Personally I find it a bit a pity that both lists goes missing when the parameter to monitor files (modified vs. opened) is changed. Would it be feasible to maintain two lists in the configuration file, where they seem to be saved, but only use one at a time in order to avoid the performance penalty we've discussed earlier?

Making users aware of the need to relaunch the application may indeed make sense. Affects other settings like the one to use system icons as well. But probably you were having these in mind anyway, too.

**Comment by tsujan** [comment]
> Would it be feasible to maintain two lists in the configuration file

Yes, it's possible but, for example, a list of "recently" opened/modified files from 2 days ago wouldn't have much meaning. Considering the fact that other editors don't have "Recently Modified", the user wouldn't need to switch between them regularly, IMO. He/she would choose one of them for a while.

> Affects other settings like the one to use system icons as well

Yes! The relaunch prompt should appear for all settings that need app restart.

**Comment by tsujan** [comment]
Added a prompt label to the Preferences dialog, which appears only when needed and can't be ignored.

The last missing feature related to session management is session saving/restoring. I agree that all opened files in all windows should be saved/restored. It needs some thought concerning the design.

**Comment by tsujan** [comment]
Session management is added. Tests and comments would be very appreciated. Please note that the session manager wasn't supposed to be that of a IDE but enough for saving and restoring sessions.

The Session Manager dialog is for saving, restoring and removing sessions. It also behaves like a prompt dialog when needed. The number of savable sessions is unlimited but that doesn't add to FeatherPad's memory or CPU usage. Sessions can be opened by the Open button of the dialog, pressing Enter when their items are selected and focused, or double clicking on their items.

**Comment by tsujan** [comment]
I think this can be closed. Session management is complete and I use it often. Feel free to reopen this if you have any suggestion. Thanks for the discussion!
