### ISSUE TITLE
Set native file dialog by default on Mac

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#229]
Qt file dialog looks really disgusting on Mac
Qt:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/19782228/51084176-8a735d80-1736-11e9-9a24-dd194034d7ba.png">
Native:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/19782228/51084182-9bbc6a00-1736-11e9-8b32-b390709bac15.png">
I would be really happy to see the native one by default :)

**Comment by shlyakpavel** [comment]
Testing these dialogs found out that "Save with encoding" does not let me choose the encoding. Neither with Qt dialogs nor with native. Ups
<img width="949" alt="image" src="https://user-images.githubusercontent.com/19782228/51084343-d8896080-1738-11e9-9f17-563bb8ba6975.png">
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/19782228/51084353-fbb41000-1738-11e9-898f-2af0b4eb0590.png">
 It is possible that I do not understand how it *should* work

**Comment by shlyakpavel** [comment]
The same on linux
<img width="742" alt="image" src="https://user-images.githubusercontent.com/19782228/51084419-7c274080-173a-11e9-8501-0eccaee31a4b.png">
I cannot understand what this feature does at all 😨

**Comment by shlyakpavel** [comment]
Upd: deleted some comments as they were my misunderstanding

**Comment by tsujan** [comment]
Native dialogs are supported on all platforms that have them but the default is non-native because, years ago, I saw serious problems in KDE (because of bugs in KDE file dialog) and didn't want FeatherPad users suffer from them by default. Of course, those KDE problems are fixed.

And yes, Qt's default file dialog is terrible -- not only on Mac.

So, your second screenshot is about FeatherPad? Then, there should be no problem. The corresponding option can be toggled by the user like other options.

That being said, I might change the default if I see no issue in some DEs.

As for "Save with Encoding" (I think you deleted the comment), it was for old MS Windows files but doesn't have a job now. However, there was no harm in keeping it.
