### ISSUE TITLE
<Ctrl><F> does not jump into Search Field in some locales

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/FeatherPad#237]
Reported here: https://forum.mxlinux.org/viewtopic.php?p=458263#p458263
and still exists in 0.9.2.

Sort of diagnosed later in the same thread:  https://forum.mxlinux.org/viewtopic.php?p=458263#p480475

**Comment by tsujan** [comment]
Thanks for reporting but I'm not responsible for translations.

I think problems like this are automatically prevented in the latest git FeatherPad because of a commit for another purpose: https://github.com/tsujan/FeatherPad/commit/2a2ccbc29ec61a1c6a585e99921dfdab64236757#diff-64e5aa874e08b4342bbfabacfe57af64 Please try the latest git; it might take a while before I publish the next release.

**Comment by tsujan** [comment]
I found some time to read a few comments in your link. I don't know about MX Linux but such problems can have 3 causes: bad builds, bad translations (shouldn't be the case with the git version) and the lack of qt5-translations (whose installation is necessary).

There's also another possibility but it isn't very likely: The shortcut may be already in use somewhere. For example, KDE has an abomination called "auto-mnemonics"; it can easily render app shortcuts unusable but FeatherPad has a workaround for that.

If you test the latest git version, please tell me about the result!
