### ISSUE TITLE
Text sent to clipboard is not plain

### ISSUE THREAD

**Issue by Vladimir-csp** [tsujan/FeatherPad#257]
Hi.
I'm migrating from Leafpad to FeatherPad as a go-to plaintext editor and noticed an issue: text copied from featherpad is not plain (at least that is how I interpret the behavior).

Steps to reproduce:
- Create a new HTML message in Thunderbird, set paragraph style to Preformat.
- Copy text from Leafpad, paste into Preformat paragraph. Pasted text retains Preformat style (or any other currently selected style)
- Copy text from FeatherPad, paste into message. "Paragraph" style is pasted with it.

**Comment by tsujan** [comment]
FeatherPad uses a `QPlainTextEdit`, which is what its name says: plain text. Whether this is a problem in `QPlainTextEdit` that needs a workaround or something else, I'll investigate. Thanks for the report!

**Comment by tsujan** [comment]
I looked into it. The problem is deep inside Qt. They treat `QPlainTextEdit` like other editors in this regard. It doesn't show up in Kate because KDE uses its own libraries.

As far as I know, you're the first Qt user who has noticed this issue. I'd encountered it before without paying attention to it.

I try to find a workaround -- as I've done on several other occasions.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/c66c5ca063cbdc354d023375e101ba0320ac0049

It also solves a problem about pasting into LibreOffice Writer -- although the latest version of LibreOffice has a clipboard bug unrelated to this report.

**Comment by Vladimir-csp** [comment]
Cool! Did you consider reporting QPlainTextEdit bug upstream?

**Comment by tsujan** [comment]
> Did you consider reporting QPlainTextEdit bug upstream?

No, because:

(1) It isn't completely in `QPlainTextEdit` but deeper, inside `QPlainTextEditControl` (which needs private headers, although the workarounds were possible without them).

(2) They don't read a report without a simple code to reproduce it -- and they have right -- but I'm too lazy to make one. This is the main reason ;)
