### ISSUE TITLE
Files are reopened in disorder

### ISSUE THREAD

**Issue by pierretom** [tsujan/FeatherPad#267]
When "Start with files of last window" is enabled, files are reopened in disorder.

**Comment by tsujan** [comment]
There's no order in opening multiple files because files are read in separate threads and loaded into the GUI whenever ready (for them to be opened as fast as possible). FeatherPad doesn't wait for the first file to be read and loaded to handle the second file, etc.

That's one of the reasons why a side-pane mode exists; in it, items are always alphabetically ordered and can be found easily by filtering. The side-pane is most suitable with sessions too.
