### ISSUE TITLE
Suspicious code

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#293]
Hello! Here is a strange thing I've found.
https://github.com/tsujan/FeatherPad/blob/1748ea7bbfacbc9e4750243adb4b4c49c014da7d/featherpad/highlighter.cpp#L3549-L3555
This code checks for openNests to be positive twice (lines 3549 and 3553). Obviously, the second check has no sense. Please, consider reviewing this code.
P. S. Did you mean `indx > 0` there?

**Comment by tsujan** [comment]
> Here is a strange thing I've found.

Oh, thanks!

I think I copy-pasted it from line 3527 (instead of typing it) and forgot to remove `openNests > 0`. Yes, it's redundant. I'll remove it.

Moreover, there is a typo there: `yamlOpenNraces` should be `yamlOpenBraces` ("N" is next to "B" in English keyboards). I should fix that too.

> P. S. Did you mean indx > 0 there?

No. `startIndx` changes in the loop.

Yaml may seem to have a simple structure but this part of its syntax highlighting was quite complex. Once I did it right, I preferred to forget it ;)

**Comment by tsujan** [comment]
My bad! You're right about `startIndx` too. I should reread it and fix these things very carefully...

**Comment by tsujan** [comment]
Done.

`indx > startIndx` was correct. `indx` goes to left until it reaches a place where there's no comment and then, `indx > startIndx` shows if there's any text to format.
