### ISSUE TITLE
Feature Request: Add hotkeys to the Save/Cancel/Discard Changes box

### ISSUE THREAD

**Issue by lightning-software** [tsujan/FeatherPad#317]
I don't know if this is a featherpad issue or an MX issue, but when I close libreoffice without saving, there are kotkeys available when holding down Alt to _D_iscard Changes, _C_ancel, or _S_ave (that's the best I could do to show they are underlined....). I really miss that in featherpad.

Is it possible to add those in, or is that an issue with MX?

**Comment by tsujan** [comment]
It isn't an issue but the lack of a feature ;)

That's called "mnemonic": when you press `Alt`, if a text has a mnemonic, it'll be underlined and its corresponding action will be activated.

I'll try to add mnemonics to the prompt dialog but they may be lost in translations (because translators haven't added it and I don't want to ruin their translations). Thanks for the report!

**Comment by tsujan** [comment]
It's done now.

I also made some changes to translations, so that the mnemonics won't be lost with them.

You could upgrade to the latest git FeatherPad or wait for the next release (0.12.0 — I'll publish it soon but I don't know when it'll come to your distro).
