### ISSUE TITLE
saving (all actions) doc with no \n at the end of the last line adds new \n

### ISSUE THREAD

**Issue by pvanek** [tsujan/FeatherPad#34]
example - a doc with no enter at the end of last line:

```
lorem ipsum
```

ctrl+s (or click icon, or select meny action)
result:

```
lorem ipsum

```
with a new line at the end of file

**Comment by tsujan** [comment]
Uncheck `Preference` → `Text` → `Ensure an empty last line on saving`. That checkbox was a feature I added later because some text editors couldn't open files without an ending newline (a user told me -- in a bug report -- that github saw such files as corrupted).

Please change some settings in Preferences to know some of FeatherPad options!
