### ISSUE TITLE
snap is broken on wayland

### ISSUE THREAD

**Issue by akvadrako** [tsujan/FeatherPad#351]
```
[17:05:40] sudo snap install featherpad
featherpad 0.10.0+pkg-3be6 from 林博仁(Buo-ren, Lin) (brlin) installed
[17:05:58] featherpad 
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

**Comment by tsujan** [comment]
I don't maintain snap and have never recommended it.

Actually, I recommend distro-specific ways.

**Comment by wxl** [comment]
Just pointing out that this is [CLEARLY marked unofficial](https://snapcraft.io/featherpad) and the packager mentions [their own bug tracker](https://github.com/Lin-Buo-Ren/featherpad-snap/issues) for support, NOT this one.

When you do go file a bug in the right place, you might want to take the effort to describe the system you're trying to install it on, including the version of `snapd` you're using.

**Comment by akvadrako** [comment]
I really don’t care. You should be grateful I went through the effort to let you know.

**Comment by wxl** [comment]
Um, OK. The Debian package works fine. So do the upstream tarballs. So this is an issue with the Snap packaging, not Featherpad. That's not our code.

**Comment by agaida** [comment]
@akvadrako - anyways - wrong place to complain

**Comment by tsujan** [comment]
> You should be grateful I went through the effort to let you know.

I am very grateful that you let me know something that doesn't have the slightest relation to my work. I also admire your intelligence.

**Comment by tsujan** [comment]
@agaida The bad thing is that I rejected things like snap from the start and yet they make noise here.

**Comment by agaida** [comment]
@tsujan - that's damn easy - put it into the bug template:

"no packaging, snap or flatpak-related things here!"

**Comment by tsujan** [comment]
Yes, I may need to add a template and tell the obvious in it.

**Comment by Lin-Buo-Ren** [comment]
Hello, I'm the maintainer of [the Featherpad snap](https://snapcraft.io/featherpad).

I would like to apologize for the late response and unnecessary disturbance caused by my snap, this shouldn't happen.  I've made several changes to mitigate the problem so that you won't be (hopefully) bothered much in the future:

* I've implemented a pre-launch prompt to proactively notify the user where to report the problem from the snap:
  ![screenshot](https://user-images.githubusercontent.com/13408130/94792840-231aa700-040c-11eb-9596-4a4d98c262e2.png)
* I've implemented a prompt that will be activated when the application is terminated prematurely, so that the user will know the exact place to report the problem if the application is crashed for whatever reasons:
  ![2020-10-01 17-38-17 的螢幕擷圖](https://user-images.githubusercontent.com/13408130/94793496-21051800-040d-11eb-9831-643117b72d4b.png)
* I've modified the [snap's store listing page](https://snapcraft.io/featherpad) to explicitly ask the user to not file snap issues to the upstream project:
  ![screenshot](https://user-images.githubusercontent.com/13408130/94793764-907b0780-040d-11eb-95c6-588ff14999e7.png)

If you have any concerns please kindly send a e-mail to <Buo.Ren.Lin@gmail.com>, or tag @Lin-Buo-Ren anywhere on GitHub, thank you.
