### ISSUE TITLE
Syntax highlighting .js file with back quote

### ISSUE THREAD

**Issue by adamjp** [tsujan/FeatherPad#375]
If I save this code snippet as a .js file:

nconf.defaults({conf: `${__dirname}/config.json`});
nconf.file(nconf.get('conf'));

Everything after the dirname} is highlighted in orange.  
If I change the back quote before the $ to a single quote, the syntax highlighting works properly.
If I take out the / before config.json it works properly also.  

If I save it as a .c file this does not happen with either a single quote or back quote.

I am running featherpad version 0.12.1 on MX Linux 19.

**Comment by tsujan** [comment]
That should be OK because the highlighter thinks they're about a regular expression.

Kate does the same thing. A screenshot:

![kate](https://user-images.githubusercontent.com/981076/78280534-7f207380-752e-11ea-9b31-4577efdc4b54.png)

Qt Creator detects an error and says, "Expected token `". So, there should be really something incorrect in your code, although, not being a JS coder, I can't tell what.

**Comment by tsujan** [comment]
A comparison with FeatherPad (the latest git):

![fpad](https://user-images.githubusercontent.com/981076/78281164-7da37b00-752f-11ea-8e43-95200b117cf9.png)

Basically, no difference.

**Comment by tsujan** [comment]
Unrelated to this but revealed by it:

I missed JS template literals in FeatherPad. Will add them soon.

**Comment by adamjp** [comment]
Thank you for reply.  This is code that I got from a book and it works, so the code is good.
Sublime and Atom highlight it correctly so, not sure what else to say.
Regardless, this is a minor issue.
Thanks again.

**Comment by tsujan** [comment]
> Regardless, this is a minor issue.

No issue is minor ;) I reopened it to investigate further. Moreover, I should include JS template literals.

Thank you very much for your report! Please also report any other problem you might encounter with JS!

**Comment by tsujan** [comment]
Back quotes (template literals) are now supported in the latest git version (https://github.com/tsujan/FeatherPad/commit/9aa06ec349a03741d72a521ef337835fb6b712e9).

No online JS validator I tried validated `nconf.defaults({conf: ${__dirname}/config.json});` but it became valid once I used back quotes. An issue in JS single and double quotes is also fixed.

So, I think the problem is solved by the latest commit. However, if you think it isn't, feel free to add comments.
