### ISSUE TITLE
Working directory / relative path issue when opening files

### ISSUE THREAD

**Issue by chriswyatt** [tsujan/FeatherPad#377]
If Featherpad is not open, and I go to a directory (e.g. `/tmp/dir1`) in a terminal, and type `featherpad file1.txt`, the file opens as expected.

If, however, `/tmp/dir1/file1.txt` is already open in Featherpad, and I try to open another file in a different directory (e.g., `cd /tmp/dir2; featherpad file2.txt`), Featherpad will complain that the file does not exist, as it tries to look for this file in the directory of the original file (i.e., `/tmp/dir1/file2.txt` rather than `/tmp/dir2/file2.txt`). I confirmed that it was using the original file's directory, by creating a file with the same name in the original directory.

I found this bug in version 0.11.1, so apologies if it has been fixed, already.

**Comment by tsujan** [comment]
Thank you very much for hunting and reporting this old issue! I encountered it once but couldn't remember how.

I'll release 0.13.2 after fixing it..

**Comment by tsujan** [comment]
Fixed alongside an unrelated minor issue in https://github.com/tsujan/FeatherPad/commit/64a6745ebaf5e26adb510b6b1ebd54484687332e

BTW, I found the reason why I'd lost the issue: it happened only when the relative path didn't contain slash. For example, `fpad ../dir2/file2.txt` worked OK inside `/tmp/dir1`.

**Comment by chriswyatt** [comment]
Thanks for the speedy resolution.

**Comment by tsujan** [comment]
You're welcome.

If it weren't for your good report, I couldn't find the problem soon (a short line of code).

BTW, 0.11.1 is very old and lacks several fixes/features. I recommend the latest git (which is always stable) or 0.13.2 (which will be released in a week or so).

**Comment by chriswyatt** [comment]
I'm on Arch, and had a bit of trouble the last time I tried to use the latest GIT version. It meant having to switch to lxqt-desktop-git, and I seem to remember it was not straight-forward (I forget why, exactly). Perhaps at some point I will set up another VM for this, as I don't want to risk breaking everything (plus, I need this laptop for work at the moment).

**Comment by tsujan** [comment]
> It meant having to switch to lxqt-desktop-git, and I seem to remember it was not straight-forward

That's correct because LXQt has many components that depend on each other.

But FeatherPad isn't a part of LXQt and doesn't depend on anything other than stable versions of Qt and Hunspell.

I just tried this and it worked fine:

You could click "Download snapshot" at https://aur.archlinux.org/packages/featherpad-git/, extract the archive, open a terminal inside it and just enter `makepkg`. The latest git will be downloaded and compiled automatically. Then, you could install it from the same terminal with `sudo pacman -U *.pkg.tar.xz`. Of course, you need to uninstall your current non-git FeatherPad first.

You could also repeat the above whenever you want to upgrade to the latest git (no need to uninstallation anymore).

**Comment by chriswyatt** [comment]
OK, thanks. I'll give that a go. I just remembered it was lxqt-archiver, I was struggling with. Patiently waiting for the next LXQt release.

**Comment by tsujan** [comment]
@chriswyatt 
I'd made a silly mistake in the commit, which interfered with FeatherPad's command-line options. But it's completely fixed now. If you've already installed the git version, please upgrade again!
