### ISSUE TITLE
Are these session behaviours intentional or for lightness?

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/FeatherPad#38]
1. No option to launch featherpad with a certain session by `featherpad SESSION-NAME`.
2. No option to retain the last open sessison.
3. File>Restore Session doesn't switch/replace sessions but adds the content of the newly restored/opened session to the existing session/files.
4. No option to automatically add newly opened files to the current session.
5. Though this is not sessions specific, neither the last edited file nor the cursor position on it is retained between launching featherpad; the cursor is always at the begining and the file in front of me is whichever is the first one in the tabs list.

**Comment by tsujan** [comment]
> No option to launch featherpad with a certain session by featherpad SESSION-NAME.

Good idea! Will think about it.

> No option to retain the last open sessison.

The last session can be saved (retained) in the session dialog with an appropriate name (date, for example).

> ile>Restore Session doesn't switch/replace sessions but adds the content of the newly restored/opened session to the existing session/files.

That's intentional. FeatherPad is a mutil-window app. The user could open another window (by tab DND, for example) and open another session in it *while keeping the current files open*.

> No option to automatically add newly opened files to the current session.

That's an overkill, IMO ;) Not really necessary.

> Though this is not sessions specific, neither the last edited file nor the cursor position on it is retained between launching featherpad;

That was in my TODO list but I was worried about too much CPU/RAM usage. However, I'll consider it later.

**Comment by AcarBurak** [comment]
Sorry for being careless: In fact the first option if enabled makes the second redundant anyway.

Well, haven't tried before, it works in the detached tab, yes.

All right, I understand the rest, thank you.

**Comment by tsujan** [comment]
I leave this issue open until (1) is implemented and restoring the cursor position is decided. Thanks again for sharing your ideas!

**Comment by AcarBurak** [comment]
How about such a scenario?

i) I've launched my freshly installed FP the first time. I haven't done any customisation yet. I see its empty window in front of me. This is its Default Session as FP works with sessions.

ii) I open some random files in that Default Session. I use the Default Session for those random files. Say, I've opened 7 files and then closed 2 of them and finally I quit FP with 5 open files/tabs. Now, based on my Options->Preferences->Files settings, when I relaunch FP I see all my last *open (5)* files in front of me in exactly the same way, cursor positions and the last *active* file retained. (So no need to manually save Sessions as well.)

iii) I've created three more sessions: SessionA, SessionB, SessionC. And every one of them works as exactly the same way the Default Session works. The only difference is that launching FP opens the Default Session, but if I want to open any other session, say SessionA I launch FP by `featherpad SessionA`.

iv) I've been working in SessionA and I need to open SessionB too. So I launch FP with that session in another window. Or I need to open a non-session file (say a config file), no problem, I open it in the Default Session. But sometimes I may just need to close SessionA and open SessionB and instead of doing that I just simply choose my desired session from a Sessions menu or toolbar; I've just instantly replaced my current open session.

**Comment by tsujan** [comment]
Of course, (ii) isn't possible in the way you described it but, instead, you could save that session and restore it. I don't think that could waste anyone's time ;) On the other hand, the saved session might be useful later.

As for (iii), I don't think adding a command-line option for sessions would make anything easier than it is already. Instead, the session dialog could be called from any window after it's closed in the first one by using `Esc`.

As for (iv), again, I don't think closing all tabs of SessionA (by right clicking on just one of them) and opening SessionB in a new tab is a difficult thing to do. Or an empty tab could be created and detached (with DND or `Ctrl+T`) if you want to use the first window for other jobs. Or....

I use the session dialog a lot, sometimes as a bookmarking tool, sometimes for opening a group of source files to read them quickly (like Qt source file), etc. Since I'm a lazy person, I need to have the fastest ways of doing things ;) IMO, there are only 2 things missing from the current session management:

(1) An option (a checkbox) in the session dialog for saving a session consisting of files that are opened in the *current* window -- in contrast to files that are opened everywhere; and

(2) Saving and restoring cursor positions (optionally?) -- a nice idea suggested by you.

Since, unlike other text editors, FeatherPad has a complete tab DND, session management will be most flexible with the above-mentioned features. Users could quickly get familiar with FeatherPad's way of session management, which may be different from other apps' but is very practical.

**Comment by tsujan** [comment]
A general word about why FeatherPad may seem "weird":

I understand that many users might have been accustomed to the common ways things are done in other apps and expect them in FeatherPad. If I was happy with those ways, I'd never thought about making yet another text editor. I didn't make FeatherPad for it just to be lightweight. Nowadays, high processing power is presupposed in most computers. What I wanted was making a text editor that could do all the needed jobs (and more) in a comfortable, minimalist way and without wasting resources or the available space. Kate was a good text editor but I got angry after using it for a while ;) gEdit was intolerable. QCreator wasn't an option.... I even started to think that the developers of those apps might not use them. So, I had to make something *different*.

**Comment by AcarBurak** [comment]
All right, thanks for the explanation.

**Comment by tsujan** [comment]
I thought about a side-pane a little. For just a few docs, there's no issue. However, theoretically, if the number of docs is high, there should be a considerable CPU usage on changing tabs because the whole list (in the side-pane) should be searched for names.

I tested my theory with Kate (which has a side pane). I opened an empty instance of Kate and dropped ~200 files with syntax highlighting into it. After that, tabs felt very "heavy". Switching a single tab required a high amount of CPU time and was slow. Even switching between 2 tabs, that were already activated, was slow and CPU-intensive.

I repeated the same experiment with FeatherPad and tabs were switched *instantly*.

I'm afraid if a side-pane has such a drawback, I couldn't want it for FeatherPad. Apps like Qt Creator are for opening a limited amount of source files but I don't like such a limitation for FeatherPad.

That being said, I'll think about it further in future.

**Comment by AcarBurak** [comment]
~200 files?

How about a combo box then, like qtcreator's? Do you dislike it?

**Comment by tsujan** [comment]
It wouldn't make any difference. An extra list of strings should be searched; the longer the list (number of tabs), the more CPU time it takes.... impractical.

When I said I might think about it further, I meant using QHash, which may be fast. The downside is that a side-pane needs *a lot of* code and if the result isn't satisfactory, all the time spent to write that code will be wasted. Not so motivating ;) especially when I have a lot of other things to do.

However, I don't consider this concluded.

**Comment by tsujan** [comment]
> ~200 files?

Yes, 200 is unrealistic; I know. But I've always tested FeatherPad under extreme circumstances for probable problems to surface.

**Comment by tsujan** [comment]
Right now, I dropped the first 120 files of `/usr/bin/` into FeatherPad, although most of them were binaries. I repeated the same thing with Kate. The difference was enormous in all respects (FeatherPad → ~190 Mb and agile, Kate → ~390 Mb and slow).

**Comment by tsujan** [comment]
The side-pane mode is implemented in a single, big commit. Some notes:

● It's as light as the tab mode :)

● It can be used temporarily (File → Show/Hide Side-Pane -- good for finding a tab among many) or permanently (Preferences → Start with side-pane mode).

● Items are always alphabetically ordered. Each item has a tooltip that shows its path and also a right-click menu, which contains various jobs when there's more than one page. Items can also be removed by middle-clicking without being selected.

● Remembering the active "tab" of a session didn't make much sence because pages can still be detached. When a session is opened, its alphabetically first file becomes visible and there's a nice filtering, with which any page can be found easily. 

● A session combo-box is not added. IMO, it would clutter the UI without having a real job because the session dialog doesn't obstruct the main window. It would also require an extra synchronization, which seems like a waste of resources to me.

Thanks for all suggestions that led to this! Waiting for probable bug reports ;)

**Comment by AcarBurak** [comment]
Works fine; thank you.

**Comment by tsujan** [comment]
You're welcome. In case you encounter any problem, please open a new issue! I've tested it a lot but, since there are complex relations between functions, bugs are possible.
