### ISSUE TITLE
Tags/labels

### ISSUE THREAD

**Issue by wibrt** [tsujan/FeatherPad#381]
A nice note taking app,

suggestion about the tags:
* don't hide the tags
* people want to reuse them
* search on them
* make them visible as the notes are on left hand side

**Comment by tsujan** [comment]
You properly meant this for https://github.com/tsujan/FeatherNotes

"Tag" is a concept I borrowed from a very old notes manager. I found it helpful but it's missing in other notes managers I've seen. It means that the user adds *hidden* descriptions to some nodes — "hidden" because he/she doesn't want to clutter the GUI but wants to find them later.

For example, you make a note as a diary and "tag" some nodes as "good day" or "problem solving". Later you could find your "good days" or cases of "problem solving" by searching in tags. Tags can also be like "good suspicious mystery"...

**Comment by wibrt** [comment]
> You properly meant this for https://github.com/tsujan/FeatherNotes

Yes, my fault

> 
> "Tag" is a concept I borrowed from a very old notes manager. I found it helpful but it's missing in other notes managers I've seen. It means that the user adds _hidden_ descriptions to some nodes — "hidden" because he/she doesn't want to clutter the GUI but wants to find them later.
> 
> For example, you make a note as a diary and "tag" some nodes as "good day" or "problem solving". Later you could find your "good days" or cases of "problem solving" by searching in tags. Tags can also be like "good suspicious mystery"...

what if there are the tags 
* Banana
* banana
* Bananas
* ..
which are essentielly all meant to be the same, but as the tags are hidding, it is hard to see which one were used in the past..

**Comment by tsujan** [comment]
Tag search is like text search: by default, it's case-insensitive and sub-strings are matched. By searching "banana", the user will find nodes with "Banana" and "Bananas" in their tags too. He/she could right-click them and see/change their tags if needed.
