### ISSUE TITLE
Please add support for admin gvfs backend

### ISSUE THREAD

**Issue by apt-ghetto** [tsujan/FeatherPad#384]
The [admin gvfs backend](https://mail.gnome.org/archives/commits-list/2016-July/msg02585.html) allows to edit files with elevated privileges, when featherpad runs with normal user privileges.

I would appreciate to see this possibility also with featherpad.

**Comment by tsujan** [comment]
FeatherPad is a Qt app without GLib dependency. GVFS admin needs GLib.

You could open FeatherPad as root with a sudo front-end (never use `sudo` itself). If you're under Wayland, you'll need XWayland.

**Comment by apt-ghetto** [comment]
Thanks for your answer.

I thought, because it works with pcmanfm-qt, that it could also work with FeatherPad.

**Comment by tsujan** [comment]
An app can be written in Qt and depend on GLib, like pcmanfm-qt. But FeatherPad is a stand-alone Qt app (not a part of LXQt).

The problem only arises under unusual circumstances, where the user runs FeatherPad under Wayland but can't use XWayland for root. At some point, I might find a solution for this artificial problem but it isn't important.

BTW, I've examined gvfs admin backend. It works with pcmanfm-qt but is good-for-nothing because so many apps aren't and won't be based on GLib.
