### ISSUE TITLE
Smart Home button feature

### ISSUE THREAD

**Issue by Wobblystep** [tsujan/FeatherPad#386]
Hello,
firstly i would like to say I appreciate your cleaner and well thought out, simpler, and more performant software and thank you for your service.

While I'm used to having the Home button take the cursor at the text start point on the current line just right past any tabulation or spaces,
 I myself don't see much use of having the cursor at the very start of the line (as it behaves now) and requires like a Ctrl+Right action to get past the tabulation and edit the text there.

Shift + Home in my experience is better off to select only the text as well.

A second press of the Home button could go to the start of the line in both cases.
 (the condition being based on text cursor position, and not on time of course)
 Additional presses can switch back and forth, incase it was mispressed.

Maybe this makes sense. Good day!

**Comment by tsujan** [comment]
There isn't any code in FeatherPad to control the behavior of `Home` or `Ctrl+Right/Left`. What you see is enforced by Qt. I didn't change them because Qt users may have got used to them.

However, I sometimes override Qt's behavior when I think it isn't reasonable — even if Qt users don't like that. In this case, I'll make `Home` go to *the start of indentation*, whatever it is — but not more.

Thanks for the suggestion!

**Comment by tsujan** [comment]
Done, as you proposed, in https://github.com/tsujan/FeatherPad/commit/0b84d52e86fce03e7e45055e4eaf96a858b1f4fb

**Comment by Wobblystep** [comment]
Oh it's completely so. Much appreciated
