### ISSUE TITLE
Error building the project from source

### ISSUE THREAD

**Issue by nathan-a-macleod** [tsujan/FeatherPad#394]
I am trying to build the project and I have successfully installed all the dependencies.
When I run the command 'cmake ..', it gives me this error:

```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find HUNSPELL: Found unsuitable version "", but required is at
  least "1.6" (found /usr/lib/x86_64-linux-gnu/libhunspell.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindHUNSPELL.cmake:13 (find_package_handle_standard_args)
  featherpad/CMakeLists.txt:14 (find_package)


**-- Configuring incomplete, errors occurred!**
See also "/home/nathanamacleod/FeatherPad/build/CMakeFiles/CMakeOutput.log".
```
And so when I run the command 'make' it gives this error:
```make: *** No targets specified and no makefile found.  Stop.```

**Comment by tsujan** [comment]
Apparently, you haven't installed "pkgconf" (or whatever its name is in your distro), which is a very basic package needed for compilation of anything with cmake. In Arch, it belongs to the `base-devel` group, which is what its name says. A list of dependencies usually presupposes that the basic packages that are needed for compilation are already installed.

Please also note that, in each distro, it's very preferable *to make an installable package* (`deb` package in Debian, `pkg.tar.xz` in Arch,  `rpm` in OpenSUSE, etc.) and then to install it — instead of installing directly from the source.

So, I highly recommend you consult your ditro's documentation for how to build installable packages from sources. In Arch-based distros, it's a piece of cake.

**Comment by urnenfeld** [comment]
The error is shown with a fresh lubuntu 20.04 installation.

I solved after installing `build-essential`

**Comment by tsujan** [comment]
> I solved after installing build-essential

Yes, `build-essential` is essential to building anything in Debian based distros.

If you know of a up-to-date and reliable Ubuntu deb package which is updated regularly, please tell me! I can add the info to INSTALL.
