### ISSUE TITLE
Printing from Dark Theme Setting

### ISSUE THREAD

**Issue by zandoval** [tsujan/FeatherPad#399]
Featherpad on MX Linux set to dark theme. Text not showing when printing out.

**Comment by tsujan** [comment]
Actually, the text is white. That's how Qt does it, not FeatherPad.

You need a dark background for printing with the dark color scheme. For example, with PDF and in `qpdfview`, the "paper" color needs to be dark. Also see https://lists.qt-project.org/pipermail/interest/2017-March/026433.html

Kate cheats by completely ignoring custom colors — even with light backgrounds — and using just one color scheme on printing:

![kate_print](https://user-images.githubusercontent.com/981076/85213262-37f99000-b371-11ea-94d9-b7319895a16c.png)

I don't think doing that in FeatherPad is a good idea. Instead, the user could switch to the light color scheme when printing — without showing whitespaces (because of a problem in Qt).

**Comment by zandoval** [comment]
Got it... Its a good fix.

**Comment by HubKing** [comment]
In my case, it seems (I tested by printing as PDF) that it prints the text/background as the screen, which is not economical. Shouldn't it invert the text/background colours for printing?

![image](https://github.com/tsujan/FeatherPad/assets/10900489/649e9478-55b7-48ba-9168-53934cd778a1)

**Comment by tsujan** [comment]
This page is very old. Printing respects the dark color scheme. Disable it if you don't want a background.
