### ISSUE TITLE
Feature request: convert tab into n spaces

### ISSUE THREAD

**Issue by Svn-Sp** [tsujan/FeatherPad#408]
Sometimes when I code in python and copy some code snippets, I get the "inconsistent use of tabs and spaces" error.
It would be a nice feature if FeatherPad would convert a tab into n spaces, whereas you can define n in the options.

**Comment by tsujan** [comment]
The number of spaces a tab corresponds to can already be defined in `Preferences → Text → Text tab size`. Also, you could create "soft tabs" (space text tabulation) by using `Ctrl+Tab` instead of `Tab` (See Help).

However, an option to covert all tabs to "soft tabs" is a good idea. I'll add an item for it soon.

Thanks for the suggestion!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/237ffc5ee62c8ec349e0839032ae8d1414659080

The new item is `Text Tabs to Spaces`. It's in the `Edit` menu and also in the right-click menu.
