### ISSUE TITLE
Select paragraph

### ISSUE THREAD

**Issue by oonet** [tsujan/FeatherPad#418]
Command to select a block of text bounded at both ends by a blank line.

Could be four clicks since three clicks selects a line. Ideally, both line select and paragraph select would be available as shortcuts.

**Comment by tsujan** [comment]
Technically speaking, a line *is* a paragraph, which is also called "a block" and should be distinguished from a "visible line" (= a  wrapped line, which depends on the window size).

In FeatherPad, a triple click selects a whole line (paragraph) minus its ending and trailing spaces (in other Qt text editors, the trailing and ending spaces are also selected but I excluded them intentionally).

Now, it's possible to *define* a paragraph as a text between empty lines, regardless of newlines ("\n") in that text. But that definition would be arbitrary. Although empty lines should be used in ordinary texts (and I've them in Help), it's better not to include "\n" inside each paragraph, so that each paragraph is really a block and can be selected by triple clicking.

**Comment by oonet** [comment]
Agreed. Wrapped lines are essentially paragraphs. Such as in this discussion.

    - On the other hand
    - This line is really part of a block
    - And this line is too
    - How to select all bulleted lines at once?

Maybe "stanzas" would be more accurate for the feature requested :-)

**Comment by tsujan** [comment]
Although I closed the report, it'll remain in my mind. If I find an acceptable implementation, I'll add it.

**Comment by oonet** [comment]
One possible option would be to have a select from <search back from cursor string> to <search forward from cursor string>. Search forward and backward is already implemented. It would be a matter of putting two searches together with text selection.

With an interface, it might make a nice "advanced" feature for user scripts :-)

**Comment by tsujan** [comment]
> With an interface, it might make a nice "advanced" feature for user scripts

I know and really miss it :(

> Search forward and backward is already implemented. It would be a matter of putting two searches together with text selection.

Simple newlines are already covered by the usual search when the user copies and pastes them into the line-edit: select a few lines, paste them into the search bar, deselect them and press F3: they will be found, selected and highlighted. But for having a non-regex newline in the search bar, there's no way other than copy-pasting (a weak point of `QLineEdit`).

As for regex, `\n` can be used in so many ways.

I should get my hands dirty again ;)

**Comment by tsujan** [comment]
Oops! I thought your comment was about newline in regex (https://github.com/tsujan/FeatherPad/issues/421); didn't check the page.

Implementing the current feature is very easy. The problem is finding a good logic for it ;)

**Comment by oonet** [comment]
Agreed :-)

And I'm curious. What are the possibilities you are considering for the logic?
