### ISSUE TITLE
Current line is sometimes highlighted without showing line numbers (Qt bug)

### ISSUE THREAD

**Issue by oonet** [tsujan/FeatherPad#419]
Highlight current line.

**Comment by tsujan** [comment]
Already implemented. The highlighting is very mild, as some users considered intense highlighting distracting. Check `Preference → Text → Always show line numbers` to highlight the current line and also to highlight its numbers (and more).

After reading this, I found out that highlighting of the current line has got a problem without `Always show line numbers`. It may be about a change/bug in a recent version of Qt. I change the title to investigate it.

**Comment by oonet** [comment]
Yes, works with line numbers :-)

Highlighting is very mild. Slightly darker might scan better. Maybe it could be configurable? (If Preferences is getting too cluttered, maybe a special tab or only in fp.conf?)

**Comment by tsujan** [comment]
> Highlighting is very mild. Slightly darker might scan better

I agree. Unfortunately, it isn't easy to find a value that's good for all eyes. I've even used a quadratic equation for extrapolation in the code but only for the light scheme. On the other hand, as you correctly guessed, I don't want to clutter Preferences -- it's already full of options. Will think about it later...

But, first, I should solve the problem that happens *without* line numbers. I'm sure it didn't exist before.

**Comment by tsujan** [comment]
Ah, there's no bug :) By design, the current line is mildly highlighted only when line numbers are shown. The mildness of the highlight isn't a problem because the line number is marked distinctively (and can be put inside the visible part of the view by double clicking the line-number strip.

There is a minor Qt bug, for which I'll add a workaround soon. It isn't directly related to this.

**Comment by oonet** [comment]
That's reasonable.

The line numbers are easy to see - but also draw the eye away from text. Makes the screen look cluttered. Line numbers also narrow the width of the window slightly (causing wraps that throw off tabs from documents edited on the same size screen in other editors). Straight text is often preferred.

As for the mildness of the highlighting, it depends upon the monitor. I tried it on several. On a couple of screens, it was a bit light but okay. On my main screen, I can hardly see it. On a page of solid text, it's hard to find even on the screens where it is visible.

Maybe just a tweak in fp.conf?

**Comment by tsujan** [comment]
> The line numbers are easy to see - but also draw the eye away from text.

I've used the current design for years — have written thousands of code lines with — and have encountered no problem.

But OK. I'll add an option for the current line color value to the bottom of Preferences → Syntax colors, although it isn't a syntax color. In that way, the GUI won't be cluttered.

**Comment by oonet** [comment]
Must be my eyes :-)

Thanks. That's helpful. Syntax colors sounds like a good place for it.

One more thing is that I don't see Syntax colors in Preferences. Maybe a newer version of FeatherPad than 0.12.1 (the latest version in Debian/Ubuntu)? If so, is there a good place to get current binaries? (Sorry to be awkward. Compile not ideal.)

**Comment by tsujan** [comment]
> Maybe a newer version of FeatherPad than 0.12.1

Oh, 0.12.1 is VERY old! The latest release is 0.15.0 and I'll release 0.16.0 soon. Old versions lack many features and may have bugs.

I don't know about Ubuntu/Debian -- maybe their maintainers don't work anymore -- but questions about installable packages should be asked downstream. You could also install FeatherPad manually but that's generally not recommended (the package manager won't know about the installed files and couldn't uninstall them).

When I was a Debian user (5 years ago), I made deb packages for my personal use. That's the best way of installing new versions of programs in Debian. It may not be easy at first but will be a piece of cake once you get familiar with it.

**Comment by oonet** [comment]
Okay, I'll be flexible :-)

It's interesting that though LXQt/Lubuntu comes bundled with FeatherPad, they just pass along the old version from Debian. It hardly does the software justice.

**Comment by tsujan** [comment]
Lubuntu uses LXQt but they always give an outdated LXQt to their users. I never understood why.

As for Debian, I just know that its previous maintainer of FeatherPad, FeatherNotes, LXQt and some other programs disappeared 6 months ago without any explanation. Debian can be very slow in getting new maintainers.

**Comment by oonet** [comment]
I wonder if people confuse FeatherPad with LeafPad?

**Comment by tsujan** [comment]
> I wonder if people confuse FeatherPad with LeafPad?

I don't think so. They are very different from each other.

**Comment by oonet** [comment]
I absolutely agree! :-)

Confusion over the name?

**Comment by tsujan** [comment]
I implemented it so that dark and light color schemes can have different highlights of the current line. The option has a tooltip that says, "Has effect only if line numbers are shown." A screenshot:

![current_line_value](https://user-images.githubusercontent.com/981076/94094122-95e3bb00-fe2b-11ea-957b-93a101bea367.png)

Will add a commit after some tests. Thanks for the idea!

**Comment by oonet** [comment]
Looks good! Glad the idea was useful :-)

Is there a reason to limit it to when line numbers are shown? This setting allows the feature to be disabled for anyone who doesn't like it. Why not also give the choice to people who do?

Also, is there a reason to have it work differently from the other color settings (a right aligned patch with the default color showing, click to change)? If "Syntax Colors" seems confusing, maybe make the tab simply "Colors" to cover everything?

**Comment by tsujan** [comment]
> Is there a reason to limit it to when line numbers are shown?

Yes, simplicity: I don't want two options for disabling/enabling them. After all, they're both about the current line.

> If "Syntax Colors" seems confusing,...

Actually, its behavior is like syntax colors: if the user activates the dark color scheme and changes it, it'll be saved for that scheme. If the user switches to the light color scheme later, the dark value will be kept intact. The reason is that dark and light backgrounds need different color values for the current line, as they need different syntax colors.

So far, so good :)

**Comment by tsujan** [comment]
BTW, your report made me add a workaround for a small Qt bug and enhance a few things. I enjoyed our discussion.

**Comment by oonet** [comment]
Simplicity is good :-)

You don't think anyone would want current line highlighting without numbers showing?

To keep things simple, why not "hide" the option in fp.conf?

Nice touch automatically swapping colors for light and dark color schemes. Is there a reason to make the current line highlight color setting look different from all the other color settings above it?

I'm curious about the Qt bug and enhancements. . . .

I enjoyed our discussion too! :-)

**Comment by tsujan** [comment]
> You don't think anyone would want current line highlighting without numbers showing?

Yes but there should be an equilibrium. The coder is in a good position to decide what is excessive and what's not, although I admit that it has a subjective aspect too.

> To keep things simple, why not "hide" the option in fp.conf?

Config files are for apps, not for users to edit them. With many apps, when you edit their config files, your changes will be overwritten.

> Is there a reason to make the current line highlight color setting look different from all the other color settings above it?

It isn't so different. Its spin box just has an extra item for the default because, by default, a translucent layer is used for highlighting the current line. The user could ignore it.

> I'm curious about the Qt bug and enhancements. . . 

The Qt bug was that, when the code didn't add any highlight, Qt added a mysterious highlight sometimes (when a text was selected). There have been so many Qt bugs that I've worked around in my apps; this one was nothing ;)

The enhancement was about telling the user that he/she needs to reopen the window for the changes to take effect. If he/she reverses all changes, the GUI should remains silent.

I may add the commit today.

**Comment by tsujan** [comment]
Oh, if you mean why it's a spin-box instead of a color button, the reason is that only the color value is needed; the color itself is always neutral = gray = (value, value, value).

**Comment by oonet** [comment]
Makes sense. I agree that gray is good design for current line highlighting. Maybe it's best to rule out poor color choices?

Just musing, is it better to have a special selection to prevent poor choices, or a simple (consistent) selection that lets people choose whatever they want (no matter how poor the choice might be)?

Might someone with color blindness benefit from a highlighting color other than gray?

Might the free choice of syntax colors make grey a poor choice for highlighting, and another color better?

**Comment by oonet** [comment]
> Yes but there should be an equilibrium. The coder is in a good position to decide what is excessive and what's not, although I admit that it has a subjective aspect too.

Agreed.

Why is current line highlighting good with line numbers but not without? (Maybe I'm not thinking clearly. I admit that I always use current line highlighting and almost never show line numbers.)

> > To keep things simple, why not "hide" the option in fp.conf?
> 
> Config files are for apps, not for users to edit them. With many apps, when you edit their config files, your changes will be overwritten.

FeatherPad doesn't have this problem :-)

Config files can allow requested or "advanced" options without cluttering up the GUI.

**Comment by tsujan** [comment]
> Just musing, is it better to have a special selection to prevent poor choices

Already implemented, within reasonable boundaries.

> Might someone with color blindness benefit from a highlighting color other than gray?

A programmer can't and shouldn't try to satisfy everyone; it's simply impossible and would result in a poor app (personal experience). Feature requests like this one are welcome because they aren't limited to special cases. I already started to use the feature for its fun ;)

> Why is current line highlighting good with line numbers but not without?

I didn't say it's bad or good. As mentioned above, I don't want two options for things that are closely related to each other.

> FeatherPad doesn't have this problem :-)

Oh, it does! And it isn't a problem. Config files of *GUI* apps can be very different from those of apps without GUI.

BTW, if you want to try the latest git version of FeatherPad *without installing it*, you could do as follows:

 * Close all FeatherPad windows.
 * Install the needed packages that are listed in the file `INSTALL` (for Debian = Ubuntu). You also need cmake but, if you've compiled things before, you may already have it.
 * Click the "Code" button on the main GitHub page of FeatherPad, download the zip file and extract it somewhere.
 * Open a terminal inside the extracted folder and enter `mkdir build && cd build`.
 * Then enter `cmake ..` and, after it, `make`.
 * After the process is completed, type `./featherpad/featherpad` and you'll see it.

**Comment by oonet** [comment]
> A programmer can't and shouldn't try to satisfy everyone; it's simply impossible and would result in a poor app (personal experience).

Agreed.

> > Why is current line highlighting good with line numbers but not without?
> 
> I didn't say it's bad or good. As mentioned above, I don't want two options for things that are closely related to each other.

Not good or bad - allowed and disallowed :-)

There are four possible combinations of the two features, only three of which are allowed:

    - Line numbers with highlighting
    - Line numbers without highlighting
    - No line numbers with highlighting (not allowed)
    - No line numbers without highlighting

My question is, why not allow all four combinations?

> > FeatherPad doesn't have this problem :-)
> 
> Oh, it does! And it isn't a problem.

Right, it's not a problem with FeatherPad like it is in some other packages. FeatherPad loads fp.conf up front - and only modifies fp.conf if a setting has been changed.

> Config files of _GUI_ apps can be very different from those of apps without GUI.

Agreed. Though no reason not to allow a larger set of options in the config files than in the GUI.

> BTW, if you want to try the latest git version of FeatherPad _without installing it_, you could do as follows:

Yes :-)
