### ISSUE TITLE
Feature request: vertically centered search results

### ISSUE THREAD

**Issue by KloudKoder** [tsujan/FeatherPad#451]
Ctrl+F works just fine for finding anything in a text file. However, it awkwardly locates the current highlighted result at the top or bottom of the page in most cases. Clearly, when searching for something, we don't just want the highlighted match itself; we want context. Therefore, it would be more useful to have the current highlighted result vertically centered, so as to have the maximum possible number of lines before and after. When the user clicks for the next result (or hits F3), then the next result should be similarly centered. When there are not enough lines present before or after the match, then the vertical centering can be done on a best-efforts basis, such that a match on the first line of the file would appear on the first line of the page, and a match on the last line of the file would appear on the last line of the page. Maximum context should be the rule.

**Comment by tsujan** [comment]
> However, it awkwardly locates the current highlighted result

It isn't awkward to me, the context isn't necessarily below or above the match, and the match isn't always at the top or bottom. You could easily find its pattern.

Kate does the same and, as far as I remember, no one has found it problematic.

> it would be more useful to have the current highlighted result vertically centered

Frankly, that seems weird to me because the text might be scrolled too much. Moreover, seeing the next match at the middle of a right/left tiled window might feel uncomfortable.

However, it can be implemented easily. Let me try it for a while. If it feels natural, I'll add a commit. If not, I'll explain why, based on my experience.

**Comment by tsujan** [comment]
OK, it didn't take long:

There are two methods: `QPlainTextEdit::setCenterOnScroll()` and `QPlainTextEdit::centerCursor()`.

The first one suddenly centers the found match when it reaches the bottom or the top of the window. A self-torture!

The second one does what you described: it keeps the match at the center as far as possible.

I'm afraid it was impractical when I tested it, especially with serious jobs like coding: while the current forward search scrolls the view only when the match is at the bottom and that depends on the window height as well as the scroll-bar position, it constantly scrolled the view, independently of everything. Quite disturbing!

**Comment by KloudKoder** [comment]
I can see how scrolling on each match might be visually annoying. All I can suggest is that it would be great if this were an option, because it's even more annoying to constantly have to back out of the search context, scroll a bit for some context, then reenter the search context. In any case, thank you for considering my feedback.
