### ISSUE TITLE
Opening too many tabs results in "previous crash detected"

### ISSUE THREAD

**Issue by KloudKoder** [tsujan/FeatherPad#453]
Select 600 text files in File Explorer. Hit Enter to open all of them in Featherpad. At first, tabs start populating as normal. But then, at some point, it starts opening new windows instead of new tabs. That's maybe OK, but the new windows all complain about a previous crash, which leads me to believe the new tab process crashed, resulting in new windows being launched instead. After that point, all further files open entire new windows.

No, I'm not smart enough to edit 600 files at once! I was just trying to debug a weird crash so I decided to stress test Featherpad.

**Comment by tsujan** [comment]
Which version?

Once in a while, I test FeatherPad under unusual circumstances — like opening ~250 files with it at once — and have never encountered a problem. Don't have a folder with 600 text files though ;)

**Comment by tsujan** [comment]
To do an extreme test, I found a way of having 789 cpp files inside the same folder by searching in a big source directory. I selected all of them and pressed Enter. It took about 30 seconds for all of them to be loaded inside a FeatherPad window cleanly and without any problem. The RAM usage was 685.9 MiB — quite acceptable for so many files, most of which had more than 500 lines.

In your case, no crash could have happened because FeatherPad is a single-process app: in the case of a crash, all tabs and windows would disappear.

If you don't have an old version of FeatherPad, please tell me to reopen this page! The latest release is 0.16.0 but 0.14.0 is also acceptable for the report.
