### ISSUE TITLE
Inconsistent order behaviour when opening files

### ISSUE THREAD

**Issue by tobiasjakobi** [tsujan/FeatherPad#503]
Hello,

I recently migrated from bluefish to featherpad and have now encountered a behaviour which breaks some of my workflows.

So when launching a new instance with multiple files, the order in which the files are opened is not consistant. Example:
featherpad --standalone bla1 bla2 bla3 bla4 bla5

I would assume that bla1 is opened in the first tab, bla2 in the second, and so forth.

However this here happens:
![screenshot_2021-04-04-163428](https://user-images.githubusercontent.com/6507947/113512304-52010980-9564-11eb-8727-47fd8ff67e50.png)

I've also seen bla1, bla5, bla4, bla3, bla2 happen, but this seems to be random.

Would it be possible to enforce some order of the tabs?

With best wishes,
Tobias

**Comment by tsujan** [comment]
I think there was an old report about it but since it might take more time to find it, I explain it here:

Multiple files are loaded in separate threads (= in parallel), not sequentially. That makes it possible to open many files as fast as possible. Therefore, the order also depends on which file can be loaded faster.

That's one of the reasons why FeatherPad has a side-pane mode (which can be made permanent in Preferences). Those who care about the order could use it. The order is always alphabetical there and the files can be filtered (see Help).

**Comment by tobiasjakobi** [comment]
Cool, thanks a lot -- that restores my workflow!

**Comment by tsujan** [comment]
You're welcome.

BTW, you may also want to try File → Save/Restore Session. It saves the cursor positions on exiting and can be combined with the side-pane mode. I use it a lot while coding.

**Comment by ralf3u** [comment]
And what about an option in the `Preferences` in `Files` for example like this with a checkbox?
`keep the order of the tabs after a restart`

**Comment by tsujan** [comment]
A checkbox wouldn't make a magic. Use the side-pane (→ https://github.com/tsujan/FeatherPad/issues/503#issuecomment-813046548).
