### ISSUE TITLE
Cannot input Modi script

### ISSUE THREAD

**Issue by abhidesh128** [tsujan/FeatherPad#516]
I was editing a TeX source where I needed to input Modi script in my content, but Modi cannot be input in FeatherPad. I can only copy-paste Modi strings from another source or editor, but cannot type it directly.

I am typing Modi with my Modi (KaGaPa Phonetic) keyboard layout on MX Linux 19.4 in FeatherPad 0.16.0. (Actually, this keyboard layout is available from xkeyboard-config ≥ 2.30, but I have installed it manually.)

I think this issue is related to Qt, but not sure about it. Is it so ?

**Comment by brucehankins** [comment]
A couple of things to note here:

1) You stated you're using MXLinux. MX, regardless of DE, is a Debian based distro. The files hosted here are from Solus, an independent distro that uses a fork of the PiSi package manager and eopkg rather than apt.

2) This would be an issue with the source or one of it's dependencies such as Qt, not with the .eopkg repackaging.

3) You've already filed an issue with the correct repository, so I'd wait for a response there https://github.com/tsujan/FeatherPad/issues/516

I did a quick Google search, but couldn't find anything relevant. Sorry, but I haven't modified the source code in anyway, and I'm definitely not a programmer, so I'm not sure how to troubleshoot. I wish you luck in finding your solution.

**Comment by tsujan** [comment]
FeatherPad supports what Qt supports.

Maybe your method of typing Modi doesn't work with Qt and you need another method for it. Sorry, I have no knowledge of Modi or how it's typed in Qt but your problem isn't cause by FeatherPad.

I transfer your report to Discussion..
