### ISSUE TITLE
Feature request: (un)indent text

### ISSUE THREAD

**Issue by KloudKoder** [tsujan/FeatherPad#525]
It would be nice to be able to select a block of text, then have a hotkey that would (un)indent by one space at a time. I realize this isn't necessarily simple because there are lots of corner cases (like the highlight beginning in the middle of a line, or no highlight actually present), but it would be really useful and would differentiate FeatherPad from most of the other editors in its class.

**Comment by tsujan** [comment]
See Help → Useful Extra (Hidden) Shortcuts:

Press `Shift+Tab` while having selected the lines. Continue pressing it if you want to remove all indentations from them; otherwise, four-space tabulations (depending on the settings) will be removed in a consistent way.

If you want to remove two-space tabulations each time, use `Shift+Meta+Tab`.

Removal of one space at a time has no practical value.

**Comment by KloudKoder** [comment]
@tsujan Fantastic! It works just fine. Maybe add this to the Edit menu so it's more easily discovered.
