### ISSUE TITLE
setting Ctrl+Tab/Ctrl+Shift+Tab to next/previous tab can't be done, because those are used IN the keyboard shortcut menu

### ISSUE THREAD

**Issue by emilBeBri** [tsujan/FeatherPad#534]
I like to have Ctrl+Tab/Ctrl+Shift+Tab bound to next/previous tab, to be consistent with my setup in Chrome and sublime text. However,  I can't change into these keyboard shortcuts, because they're active for next/previous in the keyboard shortcut setting themselves, jumping back and forth  - so when I get "press shortcut", and press Ctrl+Tab, it disables the "press shortcut" mode and goes forth - to the next keyboard shortcut!

**Comment by tsujan** [comment]
If a shortcut is consumed by your DE/WM, it can't be used by the app, of course.

However, even if `Ctrl+Tab` wasn't consumed by your DE/WM, it couldn't be used: the GUI would tell you about a reserved shortcut. This is a text editor and `Ctrl+Tab` has a more important job to do (see Help). 

`Ctrl+Shift+Tab` isn't reserved and can be used but I don't recommend `Tab` in any customized shortcut of FeatherPad; again, because this is a text editor and `Tab` appears inside several *editing* shortcuts (→ Help).
