### ISSUE TITLE
Additional colour values

### ISSUE THREAD

**Issue by tenplus1** [tsujan/FeatherPad#540]
First of all I love using Featherpad for my coding needs, and would love to see two additional entries for the "Syntax Colors" list so we can change standard "Text color" and "Background color".

**Comment by tsujan** [comment]
First, thanks for your comment!

As for the syntax colors, the user is responsible for their custom values and whether they're clearly visible. The rest is done by FeatherPad in a proper way.

The background color's *value* can already be changed in `Preferences` → `Text` but its saturation and hue are always zero and the limits for its value is chosen with the utmost care, so that the main text and also the *default* syntax colors are clearly visible against it. IMO, that's very important with a text/code editor.

As for the main text, the most important thing is its contrast with the background color, which can be changed reasonably in the above-mentioned way; hence not adding an extra option for it. I try to keep FeatherPad as simple and lightweight as possible when adding advanced features to it. This one is neither advanced nor necessary, while it complicates the code.

I'm sure there was a a similar discussion elsewhere a long time ago.
