### ISSUE TITLE
still no featherpad in Debian, but we are going to use it as the default text editor in MX 17 Linux

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/FeatherPad#55]
MX 17 is based on Debian Stretch, and is a lightweight xfce distro...but the leafpad we were using before is just too feature-poor compared to the still lightweight Featherpad.  And the homebrew MX apps are also Qt 5, so we weren't married to using gtk apps only.

The MX 17 version (I build them in Stretch pbuilder setups, so they are "clean" Stretch packages)

http://mxrepo.com/mx/repo/pool/main/f/featherpad/

I note that the 6.1 versions won't build on Jessie's gcc-4.9 any longer.

**Comment by tsujan** [comment]
Thank you for telling me about that! I released the bug-fix version 0.6.2 yesterday. Please upgrade to it!

> the leafpad we were using before is just too feature-poor compared to the still lightweight Featherpad

Although I've added many features to FeatherPad since V0.5.8, I've kept it lightweight and will continue to do so. Thanks for the feedback!

> the 6.1 versions won't build on Jessie's gcc-4.9 any longer.

That's right. gcc4 is too old; new Qt5 apps can hardly be compiled against it because they use c++11 features.

**Comment by tsujan** [comment]
BTW, this ITP is opened for Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869730

**Comment by stevenpusser** [comment]
Yes...but has any action taken place on the Debian front since July?  

Will upgrade the repo version to 0.6.2.  ;)

I'm still able to build almost any application on Jessies gcc-4.9, even if the build flags call out for std=c++11, so I suspect the issue is more complicated.  The c++14 standard is another kettle of fish, your only hope on Jessie is to try and build the app with clang, like I managed to for Polybar..

**Comment by tsujan** [comment]
> but has any action taken place on the Debian front since July?

No, as is typical of Debian ;)  (I was a Debian user for 8 years; migrated to Manjaro later)

> I'm still able to build almost any application on Jessies gcc-4.9

FeatherPad-0.5.8 could be so too. After that, I decided to use new c++ ways more freely -- they were really needed at some points -- but only as far as FeatherPad could be compiled under Ubuntu LTS.

**Comment by stevenpusser** [comment]
I was able to build 0.6.0 on Jessie, but builds failed after that.

As for Debian...this strip applies to them, too:  http://www.commitstrip.com/en/2017/10/16/wpa2-vulnerability-just-a-small-update/

**Comment by agaida** [comment]
@stevenpusser - congrats, you just added another month to the process.

**Comment by tsujan** [comment]
> As for Debian...this strip applies to them...

On Debian, I made so many personal deb packages (believe me when I say more than 100!) because they weren't in Debian repository. Sometimes, I also had to patch fundamental programs like Qt and Cairo because some Debian maintainers didn't want to apply patches that *every other distro* did -- in spite of bug reports. You could imagine how hard it was for me to "maintain" those deb packages ;) IMO, such situations weren't about "standards" at all. What they were about, I never knew..... but I think many users go to Ubuntu or mint for that very reason.

**Comment by tsujan** [comment]
As for the skeletons (in Debian's closet), I just googled for "Debian bug cairo patch tsu jan" and refreshed my old memories: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=618628. Because of that bug, I had to recompile Cairo twice a month. And that was just one example among many.
