### ISSUE TITLE
Ruby highlighting: text after slash is highlighted incorrectly

### ISSUE THREAD

**Issue by razetime** [tsujan/FeatherPad#550]
# Screenshot
![https://cdn.discordapp.com/attachments/745305489075732553/867701682903973908/a.png](https://cdn.discordapp.com/attachments/745305489075732553/867701682903973908/a.png)

Here `/` is supposed to indicate division but it doesn't seem to be treated as such.

Version is latest(0.18.0)

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/FeatherPad/commit/f6dbdb454ebac4f4a5528863ffa0978ba22a3bfc

Thank you very much for the report! It was a nasty issue.

With programming languages that I may use only rarely, such bugs can escape my attention without users' help. Please don't hesitate to report them if you encountered similar mistakes!
