### ISSUE TITLE
macOS + Qt6: error if running two instances

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#591]
If I open two Featherpad instances at once, the second one alarms me that the previous one crashed (even if it didn't)
 
![](https://user-images.githubusercontent.com/19782228/139527123-cf088037-f62b-4c7a-aa33-bcdc882554bb.png)

**Comment by tsujan** [comment]
This can be only about a socket failure and I think it's caused by a (temporary) problem in Qt6 installation on mac. Doesn't happen on Linux.

**Comment by shlyakpavel** [comment]
Update: the issue still remains today with Qt 6.2.3

**Comment by tsujan** [comment]
@shlyakpavel 
Supporting macOS is on your shoulders ;)

Please first check if the problem persists with git master. Then Search for `socketFailure_` in `singleton.cpp` and see why it becomes `true` under macOS.

**Comment by shlyakpavel** [comment]
Of course I test it on git master :)

**Comment by tsujan** [comment]
Since nothing has changed in FeatherPad in this regard, the cause should be outside it (that's also true for https://github.com/tsujan/FeatherPad/issues/593). Waiting for you to find it...

**Comment by shlyakpavel** [comment]
The problem persists with Qt 6.3.0

**Comment by tsujan** [comment]
Under Linux and with Qt 6.3.1, when I enter this in a terminal emulator, a 10-tab FeatherPad window appears without problem:
```
fpad & fpad & fpad & fpad & fpad & fpad & fpad & fpad & fpad & fpad
```
In Linux, `QStandardPaths::TempLocation` is `tmp` and the `tmp` folder is on RAM in almost all distros. Supposing that it may not be the case for macOS, I put the lock file on a relatively slow HDD to make server connection much slower. The result was the same.

Since the macOS' compilation isn't different from that of Linux *in this regard*, this should be an issue in Qt6 for macOS.

**Comment by shlyakpavel** [comment]
The issue is still there with Qt 6.3.1 and master

**Comment by tsujan** [comment]
[Qt6 doc](https://doc.qt.io/qt-6/qstandardpaths.html) says that `QStandardPaths::TempLocation` is "randomly generated" with macOS. So, there *is* a fundamental difference here.

The error happens only if either `QLocalSocket::connectToServer` or `QIODevice::write` fails. So, there may be a permission problem under macOS.

Apparently, Qt doesn't work independently of the OS where it should.

@shlyakpavel 
If you don't have time to investigate the macOS problem — *which would be completely understandable to me* — please tell me to remove the macOS support. I really don't like to make any false promise about systems other than Linux/Unix.

**Comment by shlyakpavel** [comment]
@tsujan I will try to allocate more time for these two issues soon..

**Comment by tsujan** [comment]
In the meanwhile, I'm experimenting with Qt D-Bus, to see if its effect is better than `QLocalServer`.

**Comment by tsujan** [comment]
OK, my tests show that Qt D-Bus is a better choice for creating a single-instance mode. It's much faster and smoother when more that 100 files are opened immediately after each other.

@shlyakpavel, there's no need to search for the cause of *this* issue; the code will change soon. https://github.com/tsujan/FeatherPad/issues/593 is open, but it isn't critical.

**Comment by tsujan** [comment]
Migration to Qt D-Bus is done: https://github.com/tsujan/FeatherPad/commit/60564cd55c5b188fd99609f2d3fa199cbd44b120

In addition to being more reliable than the lock-file approach, it simplified the core code a lot (`singleton.cpp`).

macOS shouldn't have a problem with it; otherwise, Qt should say goodbye to macOS ;)

I also removed the qmake support. It was redundant, and I didn't have time for it, especially with Qt D-Bus.

**Comment by shlyakpavel** [comment]
You can change this to "resolved". However, dbus connection fails on official qt 6.3.1 binaries. That causes FeatherPad exit with error code 0. 
With homebrew qt package, it works just fine!

**Comment by tsujan** [comment]
[Qt doc](https://doc.qt.io/qt-6/macos-issues.html#d-bus-and-macos) says the app should load under macOS without D-Bus functionalities. Now, it should mean that the latest git FeatherPad is a multi-process app under macOS (each window has a separate process).

Would you test that? Does the second window apppear at all? If not, there will be no point to macOS support — I don't about other non-Linux OS' — because the difference are too deep.

**Comment by tsujan** [comment]
If the app doesn't run under macOS *without D-Bus*, I still can enforce the multi-process mode (i.e., `--standalone`) for macOS in the code.

**Comment by shlyakpavel** [comment]
> [Qt doc](https://doc.qt.io/qt-6/macos-issues.html#d-bus-and-macos) says the app should load under macOS without D-Bus functionalities.

It does, but your code makes the app exit if connection is not successful

> Would you test that?

I don't quite understand you. With dbus, each time I open file with Featherpad, new tab is created. It looks like everything works just like it does in Linux. Without dbus, whenever I try to load Featherpad, it just exits with code 0.

**Comment by shlyakpavel** [comment]
Check TG, I have previously written you the details there

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/32f12141c79e0158ffe09503ff128cf552c34db7

Lack of connection is interpreted as lack of D-Bus. Please test with your macOS whether it's really the case.

**Comment by shlyakpavel** [comment]
By the way, are "close tab" buttons supposed to be visible?
<img width="812" alt="image" src="https://user-images.githubusercontent.com/19782228/179579861-c418609e-7363-43a6-8a64-4c15c5632145.png">

**Comment by shlyakpavel** [comment]
https://github.com/tsujan/FeatherPad/commit/32f12141c79e0158ffe09503ff128cf552c34db7 made things work as expected with both dbus and no-dbus environments. It's perfect now! Thank you!

**Comment by tsujan** [comment]
> By the way, are "close tab" buttons supposed to be visible?

Yes. The active Qt style draws them, not the app. There should be a problem (or "feature"?) in Qt6's macOS style.

Middle clicking closes tabs too.

> https://github.com/tsujan/FeatherPad/commit/32f12141c79e0158ffe09503ff128cf552c34db7 made things work as expected with both dbus and no-dbus environments.

Thanks a lot for testing! Now I can work on some small details related to the lack of D-Bus.

The macOS support continues :)
