### ISSUE TITLE
Crash / core dump on exit on Arch Linux

### ISSUE THREAD

**Issue by pmattern** [tsujan/FeatherPad#6]
Running a89933d on Arch Linux FeatherPad reproducibly crashes / dumps core upon exit.

It does not matter whether or not some actions had been taken after launching.
Traces where somewhat different when FeatherPad was launched in a KVM/QEMU virtual machine using the virtual QXL graphics card or bare metal and with or without Qt SVG being available so I've uploaded all of them in this [Gist](https://gist.github.com/pmattern/9590ba589d4612440f5fe93705946bc5). QMake option `CONFIG+=debug` had been set while building.

**Comment by tsujan** [comment]
Thanks for reporting!

I can't reproduce the crash here (under LXQt or Enlightenment, on an updated Manjaro Testing or an updated Debian Testing). I even left a FeatherPad window open and logged out but no coredump. The traces don't show anything specific to FeatherPad either.

Does the crash also happen if the FeatherPad window has only an empty tab?

**Comment by tsujan** [comment]
A few minutes ago, I tested under KDE Plasma too: still no crash.

**Comment by pmattern** [comment]
Desktop environments are probably not involved as the results were the same in Openbox "only" sessions without desktop environment and LXQt sessions.

The crashes happen no matter what action had been taken before. That is, when a single document is still open, a single empty tab remains or no tab at all when a single empty tab is closed before exiting.
More importantly, the crash is 100% reproducible on Debian testing running in a QEMU virtual machine here. Any chance you simply missed the crashes? A corresponding message can be seen after the crash when FeatherPad is launched from a virtual terminal. Not sure how core dumps are by default dealt with on Debian. Binary `coredumpctl` isn't available by default but included in package `systemd-coredump`. Value of sysctl parameter `kernel.core_pattern`?

On a side note there's always a message `QLocalSocket::connectToServer: Connection refused` when FeatherPad is launched from a terminal emulator. Not sure whether it's related, though, as it comes up right after launching.

**Comment by tsujan** [comment]
> Any chance you simply missed the crashes?

That's impossible. I always check "/var/lib/systemd/coredump/" because it could contain valuable info on LXQt and E (KDE always creates some files there). And yes, on Debian, I've activated coredump, although I'm on Manjaro most of the time. I also tried FP on VirtualBox with Ubuntu LTS and couldn't reproduce any crash.

I'm suspicious that those crashes may not be specific to FeatherPad on your system(s) because, first, there's no specific info on FP and, second, I've seen similar traces containing libQt5XcbQpa but for other apps. They may be related to Qt's XCB support.

> On a side note there's always a message QLocalSocket::connectToServer: Connection refused when FeatherPad is launched from a terminal emulator...

That message should be seen after a crash. Actually, after a crash, the second file won't open in the current FeatherPad window but in a separate window. That alone shows a crash has happened before.

Anyway, I'm worried about the crashes you see, especially because, whatever I do, I can't reproduce them. A few minutes ago, I was fixing a bug but your crash report caught my attention again.

**Comment by tsujan** [comment]
@pmattern 
ALthough I couldn't reproduce the crash, I added two (or three?) safeguards that should render any crash impossible. Could you please test the latest github source?

**Comment by OlivierDuchateau** [comment]
On FreeBSD with revision [c7f6246](https://github.com/tsujan/FeatherPad/tree/V0.5.7), FeatherPad crashes too. It happened when I closed the about window with following message.

QXcbConnection: XCB error: 3 (BadWindow), sequence: 2170, resource id: 15500847, major code: 40 (TranslateCoords), minor code: 0
Bus error (core dumped)

**Comment by tsujan** [comment]
@OlivierDuchateau 
Could you test the latest version (with https://github.com/tsujan/FeatherPad/commit/9f667ba533492d02a92a9795a64c9f7cb8b7c28b)?

**Comment by pmattern** [comment]
The problem seems to be fixed as of 9f667ba. It was persisting in all preceding commits, btw.
Still no clue why you couldn't reproduce it as it was 100% reproducible all the time here but anyway...

I agree the problem mentioned by @OlivierDuchateau is a different beast and think this issue can be closed.

@tsujan 
Is it on purpose that you deleted all tags / releases in this repo? In case you should consider re-adding it would be good if you could use at least annotated tags from now on as these yield somewhat more helpful output if it comes to versioning commits. Example from current master
```
$ git describe --always 
9f667ba
$ git tag -a 0.5.8 -m 'Release 0.5.8'
$ touch dummy.txt && git add . && git commit -m 'dummy commit'
$ git describe --always 
0.5.8-1-g2d2c29e
```

**Comment by tsujan** [comment]
> The problem seems to be fixed as of 9f667ba.

Wow, thanks! Fixing a unreproducible crash is a shot in the dark. Now I almost know why it happened to you. When an FP window was closed, it was also deleted in your case, so that another delete in the singleton caused a crash. But in my case, the closed window wasn't deleted and so, to prevent a memory leak, I'd added a `delete` in the singleton. It's still a mystery to me how such a big difference in behavior is possible (a Qt bug?). Anyhow, I replaced `delete` with `deleteLater` to cover both cases and to make any crash impossible.

This makes me suspect that there may be a memory leak in pcmanfm-qt because it's a single-instance app too. I'll look into that later.

> I agree the problem mentioned by @OlivierDuchateau is a different beast and think this issue can be closed.

Yes, it is. Maybe related to https://blogs.kde.org/2009/03/26/how-crash-almost-every-qtkde-application-and-how-fix-it-0. I'll open another issue for it.

> Is it on purpose that you deleted all tags / releases in this repo?

Yes! Crashing on exit was an important bug which I didn't know about until you opened this issue. So, contrary to what I thought, V0.5.7 wasn't stable. I'll release V0.5.8 soon.

**Comment by tsujan** [comment]
@OlivierDuchateau 
Your report is moved to https://github.com/tsujan/FeatherPad/issues/7

**Comment by pmattern** [comment]
>> Is it on purpose that you deleted all tags / releases in this repo?

> Yes! Crashing on exit was an important bug which I didn't know about until you opened this issue. So, contrary to what I thought, V0.5.7 wasn't stable. I'll release V0.5.8 soon.

IMO this isn't too good practice. By deleting an upstream source archive preexisting downstream packages are impaired.
So while there's no doubt point releases providing important fixes should be published ASAP I think preexisting source archives should never just get removed.

**Comment by tsujan** [comment]
@pmattern 
I agree. FeatherPad was shared only 7 months ago and I didn't want its first release to have a crashing bug. But you're right. After V0.5.8 I'll keep all releases, as I've done with Kvantum.

**Comment by tsujan** [comment]
@pmattern 
V0.5.8 released!

While updating my other manjaro installation on an old computer, I saw why github releases should be kept. Although I use the Arch-based Manjaro for 3 months, having been a Debian user for more than 6 years, I hadn't thought about that ;)

**Comment by pmattern** [comment]
A pity you still don't seem to have made an annotated tag,
```
$ git describe --always 
17c8ca4
```
see [above](https://github.com/tsujan/FeatherPad/issues/6#issuecomment-252480099) as well. IMO it would really be desirable that you consider these the next release.

**Comment by tsujan** [comment]
> A pity you still don't seem to have made an annotated tag

Sorry but with its myriad of not clearly documented commands, github would become an obstacle to me rather than a helpful tool if I engaged with it more than enough.

On the release page, there's no "annotated tag" and I really don't intend to become a github guru, for the above-mentioned reason.

**Comment by pmattern** [comment]
Basically all you need to do was already mentioned in the comment I meanwhile linked. That whole thing boils down to creating a local clone, create the tag within this clone (so not from the GitHub interface)
```
$ git tag -a 0.5.9 -m 'Release 0.5.9'
```
and push tags to GitHub
```
$ git push --tags
```
No need to be a guru, I'd say.

**Comment by tsujan** [comment]
> No need to be a guru, I'd say.

I don't know... I'll google for "github create push tags" and "github dummy commits" when I have time to become a "tagging guru", at least ;)

Anyway, many thanks for the explanation and also for your patience with my github foolishness! But above all, thank you for the crash report, without which I couldn't find and fix some other problems either!

**Comment by tsujan** [comment]
Version 0.6 released with annotated tag:
```
$ git describe --always
V0.6
```
I won't get surprised if it isn't right yet ;)
