### ISSUE TITLE
color scheme

### ISSUE THREAD

**Issue by EliaHKM** [tsujan/FeatherPad#602]
Hi,
How's it going?
I'm using Dracula theme and I would like to change the color scheme of featherpad but I don't really now how?
thanks in advance.
Have a nice day
your brother from another mother Elia

**Comment by tsujan** [comment]
Hi,

>... but I don't really now how?

I don't know what Dracula is but, most probably, you can't.

FeatherPad has two color schemes: dark and light, each with an option for setting the color value (see Preferences → Text). Also, the syntax colors can be changed for each in Preferences → Syntax Colors. I have no plan to add more than that. I only add options that may be really needed because I want to keep FeatherPad lightweight.

**Comment by EliaHKM** [comment]
thanks man.
