### ISSUE TITLE
Printing font

### ISSUE THREAD

**Issue by JonnyTech** [tsujan/FeatherPad#64]
Is it possible to change the font when printing a document?

**Comment by tsujan** [comment]
The print font is always the font you use in the document, even when you change the font temporarily and only for printing. That's the case, at least, for exporting to PDF. I haven't tested with a printer; is that different?

**Comment by JonnyTech** [comment]
I changed my document font but the printout was the same. As a workaround I shall print to PDF then print that. Thanks.

**Comment by tsujan** [comment]
> I changed my document font but the printout was the same. As a workaround I shall print to PDF then print that.

Strange! That may be a Qt bug. I'll look into it.

**Comment by tsujan** [comment]
As far as I searched the Internet, there should be no difference between PDF and real print font sizes. So, if that isn't the case, there should be a bug somewhere outside FeatherPad; in Qt or CPUS (I guess it's in Qt because a CPUS developer once told me something about bad Qt support).

If I had a printer, I could investigate the Qt issue more deeply... Closing this for now, especially because there's a workaround by printing the PDF (which happens outside Qt).
