### ISSUE TITLE
Featherpad does not respect KDE Plasma theme/font while other Qt5 apps do

### ISSUE THREAD

**Issue by JosephReza** [tsujan/FeatherPad#640]
Hello,

I am on Arch Linux running the latest KDE Plasma with the latest Qt5 (5.15.3+kde+r145-1) and Qt6 (6.0.3-3) versions installed. I updated Featherpad a few days ago, and didn't open it until now when I noticed that it is not using the Breeze Dark theme I have set for the system. Other Qt apps, whether they're KDE Plasma apps such as Dolphin File Manager or non-KDE apps such as VLC Media Player, do follow the theme.

Here is a screenshot proving this. Notice how the app below the window title bar do not use the same font or theme as the other apps (barring the actual text on the file of course):

![image](https://user-images.githubusercontent.com/28275958/166082464-d46f7aa5-7525-4916-b597-3f66ef719953.png)

**Comment by tsujan** [comment]
Arch's FeatherPad is compiled against Qt6 (with the option `-DENABLE_QT5=OFF`) and Plasma still doesn't support Qt6 styling.

The default compilation is against Qt5 and, personally, I prefer it (hence making it the default), until KDE and LXQt are ported to Qt6.

You could recompile FeatherPad by removing `-DENABLE_QT5=OFF` from https://github.com/archlinux/svntogit-community/blob/packages/featherpad/trunk/PKGBUILD and changing `pkgrel` to 3.

**Comment by FuzzyQuills** [comment]
As someone who also came across this issue, I found a workaround for LXQt that I feel shouldn't work but it's working. (I'm also on Arch Linux)

The workaround:
- Install qt5ct and qt6ct with pacman
- Set LXQt to use qt5ct by default for it's styling.
- Open qt5ct and setup your icons and theme engine in there. (I use kvantum so that's what I set)
- If qt5ct complains QT_QPA_PLATFORMTHEME isn't configured correctly, add QT_QPA_PLATFORMTHEME=qt5ct as an environment variable in LXQt's session settings.
- Now, logout and log back in to allow all the theme changes to take effect.
- Open qt6ct. If it complains about the same variable (it shouldn't and it didn't on my end) then replace the above environment variable with "qt5ct;qt6ct" < NOTE: not tested as I didn't need to do this, it may not work!
- In qt6ct, set it up the same as qt5ct. you may find it changes by itself when you click apply, that's normal.
- Now close qt6ct, open featherpad. you'll find your themes are finally respected.
Disclaimer: This issue was opened in May, there's a high chance what I'm seeing may be the result of an Arch Repo change to allow Qt5 theming in Qt6 apps, proceed at your own risk.

**Comment by tsujan** [comment]
@FuzzyQuills 
Never activate `qt5ct` under LXQt or KDE! It interferes with their icon handling and other jobs. `qt5ct` is for DE's that lack Qt5 support.

You could install and activate `qt6ct`, but you'll need to remove it as soon as LXQ or KDE are ported to Qt6.

**Comment by tsujan** [comment]
> add QT_QPA_PLATFORMTHEME=qt5ct as an environment variable in LXQt's session settings.

That's NOT recommended at all. `QT_QPA_PLATFORMTHEME` should remain `lxqt` under LXQt.
