### ISSUE TITLE
[Feature Request] Add Chinese text encoding support 

### ISSUE THREAD

**Issue by glu8716** [tsujan/FeatherPad#677]
Currently I see that FeatherPad only supports Unicode and some other Europeans encodings for text. I'd like the support for Chinese text, at least for GBK and Big5 (these are the most common ones in my experience).

**Comment by tsujan** [comment]
They were added since early versions of FeatherPad and are visible if FeatherPad is compiled against Qt5.

But,
 1.  If you've compiled FeatherPad with Qt6 (or if your distro has done it — Arch does), you won't see any encodings other than UTf-8, UTf-16 and (sub-sets of) ISO-8859-1. The reason is that Qt6 has removed all support for legacy encodings.
 2. No language needs a special encoding. UTF-8 covers all languages. It's highly recommended to covert legacy encodings to UTF-8.

Thanks for caring.
