### ISSUE TITLE
auto-save

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/FeatherPad#75]
is not a necessary feature, right?!

**Comment by tsujan** [comment]
Actually, it's among those feature that I want to implement but forget ;) FeatherNotes has auto-save, so I already have the code.

It's 2 days that I'm fighting with bash command substitution variables because their current implementation isn't free of bugs. I don't know how long it'll take but after that, I've promised to add the symlink `fpad` to the binary `featherpad`. So, the "auto-save" will come after it.

**Comment by AcarBurak** [comment]
I was not very hopeful. Thank you.

**Comment by tsujan** [comment]
Your'e welcome and thank you for the reminder!

**Comment by tsujan** [comment]
Auto-saving is implemented under Preferences → Files. Your tests would be appreciated. I think it's free of bugs but please tell me if you find any.

Some notes:

(1) Auto-saving is only for opened files, provided that they are writable and aren't removed. IMO, that makes sense because, otherwise, it might go against the user's intentions.

(2) The auto-saver always waits for heavy jobs or prompt dialogs to be done or attended to and is resumed afterwards, so that if its timeout has passed, it'll be triggered immediately.

(3) Each new window has its own auto-saver, which is started on its creation.

(4) Based on my experience with `FeatherNotes`, I've set the minimum interval to 1 min.

**Comment by AcarBurak** [comment]
Seems to work beautifully. Thank you.

**Comment by tsujan** [comment]
There was an odd mistake in the code that caused a crash on exit when auto-saving was disabled. It's fixed now :D
