### ISSUE TITLE
How about hiding both menu- and tool-bar

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/FeatherPad#76]
and provide a contextual menu entry  or just a keybinding to show one or both of them?

**Comment by tsujan** [comment]
I think a context menu with all those menus and submenus would be a mess ;) A good text-editor context menu should be only about editing, IMO.

On the other hand, removing toolbar and menubar together seems a bit of an overkill to me. I agree that the vertical space should not be overused -- and because of that, toolbar or menubar can be removed -- but a single menubar or toolbar isn't an overuse, IMO. To be honest, I even don't like the Mac-style (or Unity-style) menubar-inside-panel.

**Comment by AcarBurak** [comment]
Submenus are uncomfortable, I was thinking of just a menu entry, but never mind.

> I even don't like the Mac-style (or Unity-style) menubar-inside-panel.

I hate it; the dumbest thing to do in this era of big screens (speaking as a 20 something year Mac user until 5 years ago).

**Comment by tsujan** [comment]
> I was thinking of just a menu entry, but never mind.

Please expand on your idea! The only place that came to my mind as the editor context menu.

**Comment by AcarBurak** [comment]
Yes, I've meant a context menu entry, not a submenu under the context menu, since almost all operations of menus can be reached via keybindings… but I understand your concerns.
