### ISSUE TITLE
Change background color following system theme

### ISSUE THREAD

**Issue by Bluey26** [tsujan/FeatherPad#760]
Hello.

I use this app a lot, its my notepad by default. I would like, if its possible, to have an option or a command or a way to change the background (and the font color) whenever i change the system theme. I use LXQt as my DE, and when i change the the system theme to dark mode, the menu bars of the program changes to black, but the background does not. For that, i have to go to Preferences>Text and mark 'Dark color scheme' to see it that way(and restart the program).

Maybe its a small detail, but i find useful to have a dark background along with dark mode, but i dont know how to do it in a faster/automatic way.
If there's a command already for it, or a compile option, im glad to see it.

Thanks.

Bluey.

**Comment by tsujan** [comment]
Hi,

The background color of the text view is made independent of the style intentionally. Being a code editor and having syntax highlighting, the app can't leave it to styling, while the other widgets should follow the active Qt style for platform integration.

>  dont know how to do it in a faster/automatic way.

I'm afraid the're no faster way. Window reopening is required after a scheme change because an on-the-fly scheme change could be very CPU-intensive when many or heavy source files are opened.
