### ISSUE TITLE
Feature Request: Run through command

### ISSUE THREAD

**Issue by tim78245** [tsujan/FeatherPad#762]
Editors like KDE's Kate and MATE's Pluma have a fairly powerful feature, running the text through a command.

For example you have the following document open:

```
hello world
```

You then click Tools > Run through a command

A dialog box opens and you enter `sed "s/hello/bye/"`

It then pipes the document to the command and opens a new document:

```
bye world
```

This is probably a little heavy of a feature, but it allows the user to do anything they want.

**Comment by tsujan** [comment]
FeatherPad has this: Preferences → Files → Run executable scripts.

**Comment by tim78245** [comment]
> FeatherPad has this: Preferences → Files → Run executable scripts.

This doesn't look like the same thing.

As I understand what that does is takes the following document:

```
#!/bin/sh
echo hello world
```

and then creates a popup window that says:

```
hello world
```

It does not allow the user to pipe the current document to a command.

You can see what the feature I mean by using Kate, Tools > Filter through command.

**Comment by tsujan** [comment]
> This doesn't look like the same thing.

I didn't say it was, as I didn't mean that the feature in question wasn't valid.

I've had to do many things to keep FeatherPad lightweight and feature rich at the same time. Features are added when they fulfill certain conditions, like popularity, effectiveness, … and especially when their corresponding jobs aren't usually done by other kinds of apps (like terminal emulators or file managers).

Otherwise, you're right: this terminal-like feature could be added to a text/code editor, as https://github.com/tsujan/FeatherPad/issues/761 and many other features could. Actually, an app like Kate is a good example of feature richness with disregard for lightweightness,
