### ISSUE TITLE
Status Bar

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/FeatherPad#85]
1. Large padding between Words and syntax definition; if I decrease the window width just a tad then words count is truncated (206 instead of 2060).
2. Placements of the entries: isn't it better to put Words next to Lines and put syntax apart from all the other stats since it is not?
3. If you coders don't need to instantly see those stats, it would tidy and save space to put all of them in a drop down menu just like the syntax entry. Well, in that case it might still be tidier to put them all in the menu bar eliminating the need to show the status bar itself.
![status](https://user-images.githubusercontent.com/1426842/35899911-26bf5ae4-0be0-11e8-88cd-8645a5e02e9d.jpg)

**Comment by tsujan** [comment]
1. Yes, the left label will be covered by the right widgets if the window width is too small. There's no other way, unless I enforce a minimum width but that's not a good idea because the user may choose large fonts.

2. The words entry isn't like others. As its tooltip says, words number calculation will be CPU-intensive if done constantly. So, it's the only label that has an icon; hence its place at the end.

3. The status info is so that either the user might want to look at it repeatedly -- as I do -- or it isn't so important to the user. Because of that, the status-bar can be permanently shown or be hidden and called by a shortcut.

Showing the contents of a status-bar on a menu depends on how you look at it: you might see it as something redundant or as a special method of showing info. I think in the latter way. Menus should be called, while the status-bar is there to be looked at.

**Comment by AcarBurak** [comment]
All understandable, thanks. Just out of curiosity, how is Sel.Chars useful for you? I know what it does, but what's its purpose?

**Comment by tsujan** [comment]
The encoding, syntax and, to some extent, number of lines are important info but, IMO, the number of selected chars or words isn't. However, when it's relatively easy to show them (their codes being simple) why not? If they're covered by the right labels when the window width is small, nothing bad will happen. And, I don't know how but some users might need them.

**Comment by tsujan** [comment]
BTW, the syntax info on the left label shows the real syntax (programming language), while that of the "language label" on the right can be different and may show the enforced syntax. When they're identical, it means that no syntax is enforced.

**Comment by AcarBurak** [comment]
> […] are important info but, IMO, the number of selected chars or words isn't.

So, you've bloated fpad?! Cluttered the status bar?! Just because it's easy to bloat?:)

**Comment by tsujan** [comment]
> So, you've bloated fpad?! 

Maybe ;)

On the other hand, I see that LibreOffice Writer shows them. So, maybe, they have a value you and I don't know of.

**Comment by tsujan** [comment]
See it this way -- which is really what happened:

When I wrote FeatherPad in gtk2 ages ago, I saw that status-bar and filled it with info. When I ported the code into Qt4, I rewrote it so that the appearance was kept intact as far as possible (but the code became much cleaner). With Qt5, I didn't need a rewrite.

**Comment by AcarBurak** [comment]
Right, no problem; character needs a peculiarity!

**Comment by tsujan** [comment]
I might replace them as soon as I find more important info. Qt's statusbar can have left and right widgets and I've used all of them.

**Comment by tsujan** [comment]
Never mind! After searching the Internet, I realized that, for whatever reason, people like such stats. So, I keep them.

**Comment by AcarBurak** [comment]
Words are not meaningless, but Sel.Chars. … up to you.

**Comment by tsujan** [comment]
See how Windows users like to know the number of selected characters: https://www.cathrinewilhelmsen.net/2016/03/22/notepad-word-count/

Different combinations are possible: selected words, selected characters, all words, all chars, two of these,.... Lets's keep it as it is!

**Comment by AcarBurak** [comment]
Seeing that large selection of text … yes, it might be meaningful.
