### ISSUE TITLE
hyperlinks again

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#88]
open hyperlinks from a document in work would be useful - terminal, nano and vi can do this :)
https://www.youtube.com/watch?v=eL75dVfkjBk

**Comment by tsujan** [comment]
Agreed. Good idea!

I'll do that after releasing 0.7.1 because I want the next release to be as stable as possible.

**Comment by tsujan** [comment]
I found an interesting way to do this; "interesting" because it should be impossible with a `QPlainTextEdit` (which FeatherPad uses because of its speed) -- in a `QTextEdit`, it's a piece of cake and FeatherNotes already has it.

However, IMO, it should be limited to specific syntaxes like that of `markdown` because links can be inserted in C/C++/Python/Bash... comments and it's meaningless to open them in such places.

BTW, apparently, Kate lacks this feature, even with `markdown`. Perhaps, they thought it shouldn't be possible there ;)

**Comment by tsujan** [comment]
I willingly contradicted myself because this was so cool:

(1) Added this feature for all syntaxes that supported URL formatting.

(2) Increased the version number to 0.8 because there were several big changes since 0.7.

To detect or click a hyperlink with mouse, `Ctrl` should be first pressed and hold (the cursor will change to a hand on hyperlinks). That's intentional because otherwise, it could interfere with text editing and might take the CPU time.

Hyperlinks can be local or remote; there's no limit to them. They will be opened by appropriate apps, as far as the system knows how to open them. `perl-file-mimeinfo` (`libfile-mimeinfo-perl` in Debian) may be needed for that.

I'll add this info to Help later.

This might need some polishing later but I hope it's free of bugs.
