### ISSUE TITLE
Allow the user to bind Undo and Redo

### ISSUE THREAD

**Issue by tsimonq2** [tsujan/FeatherPad#92]
I'm personally used to pressing `Ctrl + Y` for the redo function on a text editor. FeatherPad uses `Ctrl + Shift + Z`; which is fine (changing the defaults is a separate issue), but I should be able to bind it with all the other shortcuts.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/41a254faf5c5a71b85bb447617e20ac13b03f73d.

Please note that the default Undo/Redo shortcuts are hard-coded in Qt. That means if you give `Ctrl+Y` to Redo, for example, it'll work fine but `Ctrl+Shift+Z` will work alongside it.

I didn't add Copy/Paste/.... to custom shortcuts because they are universal and I don't think users want to change them.
